object FrmManual: TFrmManual
  Left = 251
  Top = 122
  BorderStyle = bsNone
  ClientHeight = 788
  ClientWidth = 1280
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object pnManual: TPanel
    Left = 0
    Top = 0
    Width = 1280
    Height = 788
    Align = alClient
    Caption = '-'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object Panel5: TPanel
      Left = 1
      Top = 1
      Width = 1278
      Height = 35
      Align = alTop
      BevelOuter = bvNone
      Caption = 'MANUAL'
      Color = clSkyBlue
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'MS Sans Serif'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object btMan1_1: TBitBtn
      Tag = 40
      Left = 3
      Top = 40
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      OnClick = btMan1_8Click
    end
    object btMan1_7: TBitBtn
      Tag = 46
      Left = 3
      Top = 340
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      OnClick = btMan1_8Click
    end
    object btMan2_1: TBitBtn
      Tag = 50
      Left = 258
      Top = 390
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 3
      OnClick = btMan1_8Click
    end
    object btMan2_2: TBitBtn
      Tag = 51
      Left = 258
      Top = 440
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 4
      OnClick = btMan1_8Click
    end
    object btMan2_3: TBitBtn
      Tag = 52
      Left = 258
      Top = 40
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 5
      OnClick = btMan1_8Click
    end
    object btMan2_4: TBitBtn
      Tag = 53
      Left = 258
      Top = 490
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 6
      OnClick = btMan1_8Click
    end
    object btMan2_7: TBitBtn
      Tag = 56
      Left = 258
      Top = 340
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 7
      OnClick = btMan1_8Click
    end
    object btMan3_1: TBitBtn
      Tag = 60
      Left = 513
      Top = 40
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 8
      OnClick = btMan1_8Click
    end
    object btMan3_7: TBitBtn
      Tag = 66
      Left = 513
      Top = 340
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 9
      OnClick = btMan1_8Click
    end
    object btMan4_1: TBitBtn
      Tag = 70
      Left = 768
      Top = 40
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 10
      OnClick = btMan1_8Click
    end
    object btMan4_2: TBitBtn
      Tag = 71
      Left = 768
      Top = 90
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 11
      OnClick = btMan1_8Click
    end
    object btMan4_7: TBitBtn
      Tag = 76
      Left = 768
      Top = 340
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 12
      OnClick = btMan1_8Click
    end
    object btMan5_7: TBitBtn
      Tag = 76
      Left = 1023
      Top = 340
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 13
      OnClick = btMan1_8Click
    end
    object btMan5_1: TBitBtn
      Tag = 70
      Left = 513
      Top = 690
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 14
      OnClick = btMan1_8Click
    end
    object btMan4_11: TBitBtn
      Tag = 40
      Left = 768
      Top = 540
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 15
      OnClick = btMan1_8Click
    end
    object btMan2_12: TBitBtn
      Tag = 40
      Left = 258
      Top = 590
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 16
      OnClick = btMan1_8Click
    end
    object btMan4_12: TBitBtn
      Tag = 40
      Left = 768
      Top = 590
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 17
      OnClick = btMan1_8Click
    end
    object btMan2_13: TBitBtn
      Tag = 40
      Left = 258
      Top = 640
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 18
      OnClick = btMan1_8Click
    end
    object btMan4_13: TBitBtn
      Tag = 40
      Left = 768
      Top = 640
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 19
      OnClick = btMan1_8Click
    end
    object btMan5_13: TBitBtn
      Tag = 40
      Left = 1023
      Top = 640
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 20
      OnClick = btMan1_8Click
    end
    object btMan2_14: TBitBtn
      Tag = 40
      Left = 258
      Top = 690
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 21
      OnClick = btMan1_8Click
    end
    object btMan4_14: TBitBtn
      Tag = 40
      Left = 768
      Top = 690
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 22
      OnClick = btMan1_8Click
    end
    object btMan5_14: TBitBtn
      Tag = 40
      Left = 1023
      Top = 690
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 23
      OnClick = btMan1_8Click
    end
    object btMan6_9: TBitBtn
      Tag = 40
      Left = 1278
      Top = 440
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 24
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_8: TBitBtn
      Tag = 40
      Left = 1278
      Top = 390
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 25
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_7: TBitBtn
      Tag = 76
      Left = 1278
      Top = 340
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 26
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_6: TBitBtn
      Tag = 64
      Left = 1278
      Top = 290
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 27
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_5: TBitBtn
      Tag = 63
      Left = 1278
      Top = 240
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 28
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_4: TBitBtn
      Tag = 62
      Left = 1278
      Top = 190
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 29
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_3: TBitBtn
      Tag = 61
      Left = 1278
      Top = 140
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 30
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_2: TBitBtn
      Tag = 71
      Left = 1278
      Top = 90
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 31
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_1: TBitBtn
      Tag = 70
      Left = 1278
      Top = 40
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 32
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_11: TBitBtn
      Tag = 40
      Left = 1278
      Top = 540
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 33
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_12: TBitBtn
      Tag = 40
      Left = 1278
      Top = 590
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 34
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_13: TBitBtn
      Tag = 40
      Left = 1278
      Top = 640
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 35
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_14: TBitBtn
      Tag = 40
      Left = 1278
      Top = 690
      Width = 255
      Height = 50
      Enabled = False
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 36
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan6_10: TBitBtn
      Tag = 40
      Left = 1278
      Top = 490
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 37
      Visible = False
      OnClick = btMan1_8Click
    end
    object btMan4_10: TBitBtn
      Tag = 40
      Left = 768
      Top = 492
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 38
      OnClick = btMan1_8Click
    end
    object btMan4_9: TBitBtn
      Tag = 40
      Left = 768
      Top = 444
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 39
      OnClick = btMan1_8Click
    end
    object btMan5_12: TBitBtn
      Tag = 40
      Left = 1023
      Top = 590
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 40
      OnClick = btMan1_8Click
    end
    object btMan5_11: TBitBtn
      Tag = 40
      Left = 1023
      Top = 540
      Width = 255
      Height = 50
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 41
      OnClick = btMan1_8Click
    end
  end
  object tmUpdate: TTimer
    Enabled = False
    Interval = 100
    OnTimer = tmUpdateTimer
    Left = 16
    Top = 16
  end
end
