//---------------------------------------------------------------------------

#ifndef FormDeviceSetH
#define FormDeviceSetH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Buttons.hpp>
#include <jpeg.hpp>
#include <Grids.hpp>
//---------------------------------------------------------------------------
#include "Timer.h"
#include "FrameMotr.h"
#include "FrameCylOneBt.h"
#include "FrameOutPut.h"
#include <ImgList.hpp>
class TFrmDeviceSet : public TForm
{
__published:	// IDE-managed Components
    TTimer *tmUpdateTimer;
        TImageList *ImageList1;
        TPageControl *pcDeviceSet;
        TTabSheet *tsDeviceInfo;
        TGroupBox *GroupBox10;
        TImage *Image2;
        TLabel *Label10;
        TLabel *Label11;
        TLabel *Label12;
        TLabel *Label13;
        TStaticText *lbRowPitch;
        TEdit *edRowPitch;
        TStaticText *lbColPitch;
        TEdit *edColPitch;
        TStaticText *lbRowGroupCount;
        TEdit *edRowGroupCount;
        TStaticText *lbColCount;
        TEdit *edColCount;
        TStaticText *lbRowGroupGap;
        TEdit *edRowGroupGap;
        TStaticText *lbColGroupGap;
        TEdit *edColGroupGap;
        TStaticText *lbRowCount;
        TEdit *edRowCount;
        TStaticText *lbSrColCntrPitch;
        TEdit *edColGroupCount;
        TGroupBox *GroupBox11;
        TImage *Image3;
        TStaticText *StaticText8;
        TEdit *edCsSlotCnt;
        TStaticText *StaticText10;
        TEdit *edCsSlotPitch;
        TTabSheet *tsLoader;
        TImage *Image7;
        TGroupBox *GroupBox1;
        TPanel *pnLDR_ZCmpPos;
        TGroupBox *GroupBox23;
        TPanel *pnLDR_YCmpPos;
        TPanel *Panel6;
        TRadioGroup *rgLDRJogUnit;
        TEdit *edLDRJogUnit;
        TPageControl *PageControl3;
        TTabSheet *TabSheet8;
        TTabSheet *tsRail;
        TGroupBox *GroupBox5;
        TPanel *pnPRB_XIdxPos;
        TGroupBox *GroupBox24;
        TPanel *pnPSB_XIdxPos;
        TPanel *Panel1;
        TPageControl *PageControl1;
        TTabSheet *TabSheet2;
        TRadioGroup *rgRALJogUnit;
        TEdit *edRALJogUnit;
        TTabSheet *tsProbe;
        TGroupBox *GroupBox7;
        TPanel *pnWRK_ZTopPos;
        TGroupBox *GroupBox8;
        TPanel *pnWRK_ZBtmPos;
        TButton *btInspStart;
        TButton *btToolChange;
        TStringGrid *sgProbeCrnt;
        TPanel *pnProbeMotr;
        TPanel *Panel2;
        TPageControl *PageControl2;
        TTabSheet *TabSheet6;
        TRadioGroup *rgWRKJogUnit;
        TEdit *edWRKJogUnit;
        TTabSheet *tsSortTool;
        TGroupBox *GroupBox29;
        TPanel *pnSTL_YTopPos;
        TPanel *Panel31;
        TRadioGroup *rgSTLJogUnit;
        TEdit *edSTLJogUnit;
        TPageControl *PageControl5;
        TTabSheet *TabSheet11;
        TTabSheet *tsUnLoader;
        TImage *Image9;
        TGroupBox *GroupBox25;
        TPanel *pnULD_YCmpPos;
        TGroupBox *GroupBox26;
        TPanel *pnULD_ZCmpPos;
        TPanel *Panel26;
        TRadioGroup *rgULDJogUnit;
        TEdit *edULDJogUnit;
        TPageControl *PageControl4;
        TTabSheet *TabSheet10;
        TBitBtn *btSaveDevice;
        TTabSheet *tsOption;
        TPageControl *PageControl6;
        TTabSheet *TabSheet21;
        TTabSheet *TabSheet22;
        TPanel *Panel9;
        TLabel *Label9;
        TLabel *Label14;
        TLabel *Label27;
        TLabel *Label28;
        TPanel *Panel12;
        TImage *Image6;
        TLabel *Label32;
        TEdit *edLotEndMgzCnt;
        TEdit *edWaitDelay;
        TGroupBox *gbPinSetting;
        TStaticText *StaticText6;
        TStaticText *StaticText7;
        TComboBox *cb2Ch1P;
        TStaticText *StaticText12;
        TStaticText *StaticText9;
        TComboBox *cb2Ch1N;
        TComboBox *cb1Ch1P;
        TComboBox *cb1Ch1N;
        TComboBox *cb2Ch2P;
        TStaticText *StaticText32;
        TStaticText *StaticText33;
        TComboBox *cb2Ch2N;
        TComboBox *cb1Ch2P;
        TComboBox *cb1Ch2N;
        TComboBox *cb2Ch3P;
        TStaticText *StaticText34;
        TStaticText *StaticText35;
        TComboBox *cb2Ch3N;
        TComboBox *cb1Ch3P;
        TComboBox *cb1Ch3N;
        TImage *Image4;
        TImage *Image1;
        TGroupBox *GroupBox16;
        TEdit *edZennerHigh;
        TEdit *edZennerLow;
        TEdit *ed1ChLow;
        TEdit *ed1ChHigh;
        TStaticText *StaticText11;
        TStaticText *StaticText14;
        TEdit *ed2ChLow;
        TEdit *ed2ChHigh;
        TStaticText *StaticText19;
        TStaticText *StaticText20;
        TStaticText *StaticText21;
        TCheckBox *cbUseZenner;
        TGroupBox *GroupBox17;
        TLabel *Label19;
        TLabel *Label20;
        TLabel *Label23;
        TLabel *Label24;
        TLabel *Label25;
        TLabel *Label26;
        TStaticText *StaticText39;
        TEdit *ed1ChDelay;
        TStaticText *StaticText40;
        TEdit *ed1ChLedTime;
        TStaticText *StaticText41;
        TEdit *ed1ChZenTime;
        TStaticText *StaticText42;
        TEdit *ed2ChDelay;
        TStaticText *StaticText43;
        TEdit *ed2ChLedTime;
        TStaticText *StaticText44;
        TEdit *ed2ChZenTime;
        TGroupBox *GroupBox14;
        TLabel *Label8;
        TEdit *edContactCnt;
        TStaticText *StaticText22;
        TStaticText *StaticText1;
        TEdit *edReInspCnt;
        TStaticText *StaticText36;
        TEdit *edLimInsFailCnt;
        TEdit *edPinCnt;
        TStaticText *StaticText29;
        TEdit *edPrbSttDelay;
        TStaticText *StaticText38;
        TGroupBox *gbProbeTest;
        TLabel *Label15;
        TLabel *Label16;
        TEdit *edProbeTime;
        TBitBtn *btStartTest;
        TBitBtn *btStopTest;
        TEdit *edPinNumber;
        TMemo *mmProbeTest;
    TPanel *Panel14;
    TLabel *Label49;
    TLabel *Label50;
    TLabel *Label51;
    TLabel *Label52;
    TPanel *Panel15;
    TImage *Image12;
    TLabel *Label57;
    TEdit *edPSBReGripCol;
    TEdit *edPSBReGripOfs;
    TButton *btPSBAutoCAL;
    TImage *Image13;
    TImage *Image14;
    TGroupBox *gbDaegyeom;
    TLabel *Label46;
    TStaticText *lbSwitchingDly;
    TEdit *edSwitchingDly;
    TLabel *lbTrimPtchOfs;
    TLabel *Label62;
    TEdit *edTrimPtchOfs;
        TLabel *Label63;
        TLabel *Label64;
        TEdit *edTrimRjtDly;
        TGroupBox *gbProbeComTest;
        TButton *btPbSet;
        TButton *btPbStart;
        TButton *btPbOpen;
        TButton *btPbClose;
        TCheckBox *cbChRvsCrnt;
        TCheckBox *cbUseTwiceInsp;
    TStaticText *StaticText13;
    TEdit *ed1ChLedCur;
    TEdit *ed2ChLedCur;
    TLabel *Label6;
    TLabel *Label7;
    TStaticText *StaticText37;
    TEdit *ed1ChZenCur;
    TEdit *ed2ChZenCur;
        TGroupBox *GroupBox15;
        TStaticText *StaticText15;
        TEdit *edContactPinCnt;
        TBitBtn *brContactCntReset;
        TStaticText *StaticText54;
        TEdit *edLimContactPinCnt;
    TPanel *Panel39;
        TBitBtn *btSTL_YPchFw;
        TBitBtn *btSTL_YPchBw;
    TStaticText *StaticText55;
        TStaticText *StaticText47;
        TEdit *edDgChipCnt;
        TLabel *Label58;
        TGroupBox *GroupBox9;
        TPanel *pnWRK_YBtmPos;
    TGroupBox *GroupBox21;
        TPanel *pnMotrJog10;
    TGroupBox *GroupBox22;
        TPanel *pnMotrJog11;
    TGroupBox *GroupBox2;
        TPanel *pnMotrJog0;
    TGroupBox *GroupBox3;
        TPanel *pnMotrJog1;
    TGroupBox *GroupBox13;
        TPanel *pnMotrJog2;
    TGroupBox *GroupBox18;
        TPanel *pnMotrJog5;
    TGroupBox *GroupBox20;
        TPanel *pnMotrJog6;
    TGroupBox *GroupBox27;
        TPanel *pnMotrJog7;
    TGroupBox *GroupBox34;
        TPanel *pnMotrJog12;
    TGroupBox *GroupBox35;
        TPanel *pnMotrJog13;
        TGroupBox *GroupBox28;
        TPanel *pnMotrJog8;
        TGroupBox *GroupBox32;
        TPanel *pnRJT_XBtmPos;
        TCheckBox *cbSideLEDControl;
        TPanel *Panel32;
        TLabel *Label22;
        TLabel *Label31;
        TPanel *Panel33;
        TImage *Image11;
        TLabel *Label41;
        TEdit *edWRKPtchOfs;
        TPanel *Panel24;
        TLabel *Label39;
        TLabel *Label40;
        TPanel *Panel25;
        TImage *Image10;
        TLabel *Label38;
        TEdit *edREJPitch;
        TTabSheet *TabSheet1;
        TPanel *pnSetVisn;
        TGroupBox *GroupBox70;
        TPanel *pnWRK_XBtmPos;
        TGroupBox *GroupBox71;
        TPanel *pnMotrJog4;
        TLabel *Label48;
        TLabel *Label53;
        TEdit *edRejectMoveDeley;
        TStaticText *StaticText26;
        TEdit *edFrtPrcFailCnt;
        TStaticText *StaticText27;
        TEdit *edRowSubGroupGap;
        TStaticText *StaticText28;
        TEdit *edRowSubGrCount;
        TGroupBox *GroupBox19;
        TPanel *pnWRK_YCamPos;
        TTabSheet *TabSheet3;
        TGroupBox *GroupBox4;
        TPanel *pnMotrJog3;
        TGroupBox *GroupBox49;
        TPanel *pnMotrJog9;
        TPanel *pnAtcr0;
        TPanel *pnAtcr1;
        TPanel *pnIO1;
        TPanel *pnIO2;
        TPanel *pnAtcr2;
        TPanel *pnAtcr3;
        TPanel *pnAtcr4;
        TPanel *pnAtcr6;
        TPanel *pnAtcr7;
        TPanel *pnAtcr10;
        TPanel *pnIO3;
        TPanel *pnAtcr5;
        TPanel *pnAtcr8;
        TPanel *pnAtcr9;
        TPanel *pnAtcr11;
        TPanel *pnIO7;
        TPanel *pnIO6;
        TPanel *pnAtcr12;
        TGroupBox *GroupBox6;
        TPanel *pnSpare;
        TLabel *Label1;
        TEdit *edWorkXWaitOfs;
        TLabel *Label2;
        TPanel *pnIO4;
        TPanel *pnIO5;
        TPanel *Panel3;
        TLabel *Label3;
        TLabel *Label4;
        TPanel *Panel4;
        TImage *Image5;
        TLabel *Label18;
        TEdit *edPRBRlrDelay;
        TLabel *Label5;
        TLabel *Label17;
        TEdit *edPRBRlrOffDelay;
        TButton *Button1;
        TPanel *Panel5;
        TRadioGroup *RadioGroup1;
        TEdit *Edit1;
        TPageControl *PageControl7;
        TTabSheet *TabSheet5;
        TGroupBox *GroupBox36;
        TPanel *pnWRK_Visn;
        TLabel *Label21;
        TEdit *edWRKZTopSpeed;
        TLabel *Label29;
        TCheckBox *cbWRKZTopRepeat;
    void __fastcall btSavePosClick(TObject *Sender);
    void __fastcall tmUpdateTimerTimer(TObject *Sender);
    void __fastcall FormDestroy(TObject *Sender);
    void __fastcall FormShow(TObject *Sender);
        void __fastcall pcDeviceSetChange(TObject *Sender);
    void __fastcall btStartTestClick(TObject *Sender);
        void __fastcall mmProbeTestDblClick(TObject *Sender);
        void __fastcall btToolChangeClick(TObject *Sender);
        void __fastcall btResetRptClick(TObject *Sender);
    void __fastcall btLDR_InClick(TObject *Sender);
    void __fastcall btInspStartClick(TObject *Sender);
    void __fastcall btStopTestClick(TObject *Sender);
    void __fastcall btPSBAutoCALClick(TObject *Sender);
        void __fastcall brContactCntResetClick(TObject *Sender);
    void __fastcall btSTL_YPchFwClick(TObject *Sender);
        void __fastcall rgLDRJogUnitClick(TObject *Sender);
        void __fastcall btLDR_CmpClick(TObject *Sender);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
        void __fastcall Button1Click(TObject *Sender);
private:	// User declarations
    //Active Radio Button Page.
    TRadioGroup  * rgUnitUser ;
    TEdit        * edUnitUser ;
    CDelayTimer    m_tmProbeTest ;
public:		// User declarations
    TFraMotr      *FraMotor   [MAX_MOTR];
    TFraCylOneBt  *FraCylinder[MAX_ACTR];

    TFraOutput    *foLDRAcIn  ;
    TFraOutput    *foLDRAcOut ;
    TFraOutput    *foPREAc    ;
    TFraOutput    *foPSBAc    ;
    TFraOutput    *foPSBBlwr  ;
    TFraOutput    *foULDACIn  ;
    TFraOutput    *foULDAcOut ;

    __fastcall TFrmDeviceSet(TComponent* Owner);
    void __fastcall UpdateDevInfo(bool bTo);
    void __fastcall UpdateDevOptn(bool bTo);
    void __fastcall MtWindowSet() ;
    void __fastcall AtWindowSet() ;
    void __fastcall ShowSet    () ;
};
//---------------------------------------------------------------------------
extern PACKAGE TFrmDeviceSet *FrmDeviceSet;
//---------------------------------------------------------------------------
#endif
