//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HVSystem.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_HVSYSTEM_FORM               101
#define IDR_MAINFRAME                   128
#define IDR_HVSYSTTYPE                  129
#define IDD_TITLE_BAR                   130
#define IDD_BOTTOM_BAR                  131
#define IDD_IMG_DISPLAY                 132
#define IDD_DISPLAY_COMM                139
#define IDD_CONTROL_PANEL               141
#define IDB_EXITN                       142
#define IDB_EXITU                       144
#define IDB_EXITD                       145
#define IDB_GRABN                       147
#define IDB_GRABU                       149
#define IDB_GRABD                       150
#define IDB_LIVEN                       151
#define IDB_LIVEU                       152
#define IDB_LIVED                       153
#define IDD_DIALOG_MESSAGE              157
#define IDB_TESTN                       241
#define IDB_TESTU                       242
#define IDB_BTN_MASK13045               243
#define IDB_CTRLSTAGE_MANUAL            244
#define IDB_CTRLSTAGE_AUTO              245
#define IDB_TESTD                       246
#define IDB_TESTI                       247
#define IDD_IO_CONTROL                  252
#define IDB_IOMASK                      254
#define IDB_IOON                        255
#define IDB_IOOFF                       257
#define IDB_SETUP_BTNMASK               274
#define IDB_TITLE_SYSMENU               278
#define IDB_TITLE_SYSMENUMASK           279
#define IDB_TITLE_SYSMENUD              280
#define IDB_AUTON                       283
#define IDB_AUTOI                       284
#define IDB_AUTOD                       285
#define IDB_EXITI                       286
#define IDB_AUTOU                       287
#define IDD_CNTWIN                      288
#define IDB_HANRALOGO                   291
#define IDB_HANRALOGOMASK               292
#define IDB_SLEDM                       294
#define IDB_SLEDD                       295
#define IDB_SLEDN                       296
#define IDD_DIALOG_TABWIN               297
#define IDB_MOTIONTABM                  299
#define IDD_DIALOG_TABDATA              301
#define IDB_DATATABD                    302
#define IDB_DATATABN                    303
#define IDD_DIALOG_TABSETUP             304
#define IDB_SETUPTABN                   305
#define IDB_SETUPTABD                   306
#define IDB_SETUP_SAVED                 314
#define IDB_SETUP_SAVEN                 327
#define IDB_SETUP_SAVEU                 328
#define IDB_RESETN                      329
#define IDB_RESETD                      330
#define IDB_CTRLBTNMASK2                331
#define IDB_RESETI                      332
#define IDB_RESETU                      333
#define IDB_LIVEI                       343
#define IDB_GRABI                       347
#define IDB_TITLE_SYSMENUCHECK          348
#define IDD_DIALOG_3DDISPLAY            353
#define IDD_DIALOG_OKNG                 354
#define IDB_SAVEN                       356
#define IDB_SAVEU                       357
#define IDB_OKNG_MASK                   358
#define IDB_SAVED                       359
#define IDB_SAVEI                       360
#define IDB_LOKN                        361
#define IDB_LNGN                        362
#define IDB_AOKN                        363
#define IDB_ANGN                        364
#define IDB_TOKN                        365
#define IDB_TNGN                        366
#define IDD_DIALOG_3DMODEL              367
#define IDD_IMG2_DISPLAY                368
#define IDD_DIALOG_HPROJ                369
#define IDD_DIALOG_VPROJ                370
#define IDD_DIALOG_ANGLE                371
#define IDB_SETUP_APPLYN                372
#define IDB_SETUP_APPLYD                373
#define IDB_SETUP_APPLYU                374
#define IDB_PASSWDN                     377
#define IDB_PASSWDD                     378
#define IDB_3DSAVEM                     382
#define IDB_3DSAVED                     383
#define IDB_3DSAVEN                     384
#define IDD_DIALOG_TABCDATA             385
#define IDB_CDATATABD                   388
#define IDB_CDATATABN                   389
#define IDB_3DMODELD                    390
#define IDB_3DMODELN                    391
#define IDB_RNG                         392
#define IDB_ROK                         393
#define IDB_SNG                         394
#define IDB_SOK                         395
#define IDB_PNG                         396
#define IDB_POK                         397
#define IDB_HNG                         398
#define IDB_HOK                         399
#define IDB_ABCENTERD                   400
#define IDB_ABCENTERN                   401
#define IDB_MASN                        402
#define IDB_MASD                        403
#define IDD_DIALOG_PASSINPUT            404
#define IDB_OKCANCELMASK                405
#define IDB_OKN                         406
#define IDB_OKD                         407
#define IDB_CANCELN                     408
#define IDB_CANCELD                     409
#define IDD_DIALOG_PASSMODIFY           410
#define IDB_DEFAULTN                    411
#define IDB_DEFAULTD                    412
#define IDD_DIALOG_MOVE                 413
#define IDB_MASKARROW                   414
#define IDB_DOWNARROWD                  417
#define IDB_DOWNARROWN                  418
#define IDB_DOWNARROWU                  419
#define IDB_LEFTARROWD                  420
#define IDB_LEFTARROWN                  421
#define IDB_LEFTARROWU                  422
#define IDB_RIGHTARROWD                 423
#define IDB_RIGHTARROWN                 424
#define IDB_RIGHTARROWU                 425
#define IDB_STOPARROWD                  426
#define IDB_STOPARROWN                  427
#define IDB_STOPARROWU                  428
#define IDB_UPARROWD                    429
#define IDB_UPARROWN                    430
#define IDB_UPARROWU                    431
#define IDB_RSAVEI                      434
#define IDB_RSAVEN                      435
#define IDB_RSAVED                      436
#define IDB_RSAVEU                      437
#define IDB_AOP                         438
#define IDB_MOP                         439
#define IDD_DIALOG_TABETC               440
#define IDB_ETCD                        441
#define IDB_ETCN                        442
#define IDB_MASK100x50                  444
#define IDB_MASTERD                     445
#define IDB_MASTERN                     446
#define IDB_OCMASK100x50                447
#define IDB_CANCELD100x50               448
#define IDB_CANCELN100x50               449
#define IDB_CANCELU100x50               450
#define IDB_OKD100x50                   451
#define IDB_OKN100x50                   452
#define IDB_OKU100x50                   453
#define IDB_LINKM                       454
#define IDB_LINKN                       455
#define IDB_LINKD                       456
#define IDB_BITMAP1                     457
#define IDB_SUBN                        459
#define IDB_SUBD                        460
#define IDB_SUBM                        461
#define IDD_IMG3_DISPLAY                462
#define IDB_B80X40U                     463
#define IDB_B80X40D                     464
#define IDB_B80X40IM                    465
#define IDB_B80X40M                     466
#define IDB_B80X40N                     467
#define IDD_DIALOG1                     469
#define IDD_DIALOG_TAB_M_BASE           469
#define IDD_DIALOG_TAB_M_IO             470
#define IDB_M_MOTION_UNCLICKED          479
#define IDB_M_IO_CLICKED                480
#define IDB_M_IO_UNCLICKED              481
#define IDB_M_MOTION_CLICKED            482
#define IDD_DIALOG_TAB_M_MOTION         483
#define IDD_CAMERA_CONTROL              484
#define IDB_IO_BTN_MASK                 486
#define IDB_IO_BTN                      487
#define IDB_IO_BTN_CLICK                488
#define IDB_IO_APC_BTN_MASK             489
#define IDB_IO_APC_BTN                  490
#define IDB_IO_APC_BTN_CLICKED          491
#define IDB_IO_APC_POWER_BTN            492
#define IDB_TITLE_LEFT                  493
#define IDB_TITLE_RIGHT                 494
#define IDB_TITLE_M                     495
#define IDC_LIST_COMM_EVENT             1001
#define IDC_BUTTON_EXIT                 1003
#define IDC_BUTTON_GRAB                 1004
#define IDC_BUTTON_LIVE                 1005
#define IDC_BUTTON_TEST                 1008
#define IDC_BUTTON_AUTO                 1009
#define IDC_BUTTON_SAVE                 1010
#define IDC_BUTTON_RESET                1011
#define IDC_BUTTON_RSAVE                1012
#define IDC_IO_IN0                      1059
#define IDC_IO_IN1                      1060
#define IDC_IO_IN2                      1061
#define IDC_IO_IN3                      1062
#define IDC_IO_IN4                      1063
#define IDC_IO_IN5                      1064
#define IDC_IO_IN6                      1065
#define IDC_IO_IN7                      1066
#define IDC_IO_OUT0                     1067
#define IDC_IO_OUT8                     1068
#define IDC_IO_IN8                      1069
#define IDC_IO_IN9                      1070
#define IDC_STATIC_MESSAGE              1070
#define IDC_IO_IN10                     1071
#define IDC_IO_IN11                     1072
#define IDC_IO_IN12                     1073
#define IDC_IO_IN13                     1074
#define IDC_IO_OUT1                     1075
#define IDC_IO_OUT2                     1076
#define IDC_IO_OUT3                     1077
#define IDC_IO_OUT4                     1078
#define IDC_IO_OUT5                     1079
#define IDC_IO_OUT6                     1080
#define IDC_IO_OUT7                     1081
#define IDC_IO_OUT9                     1082
#define IDC_IO_OUT10                    1083
#define IDC_IO_OUT11                    1084
#define IDC_IO_OUT12                    1085
#define IDC_IO_OUT13                    1086
#define IDC_IO_OUT14                    1087
#define IDC_IO_OUT15                    1088
#define IDC_IO_IN14                     1089
#define IDC_IO_IN15                     1090
#define IDC_BUTTON_SYSMENU_COMM         1143
#define IDC_BUTTON_SYSMENU_CONTROL      1145
#define IDC_EDIT_MINUTE                 1146
#define IDC_BUTTON_SYSMENU_CONTROL2     1146
#define IDC_EDIT_PIXEL                  1147
#define IDC_CNT_NAME1                   1148
#define IDC_EDIT_DISPTYPE               1148
#define IDC_CNT_NAME2                   1149
#define IDC_BUTTON_HANRALOGO            1149
#define IDC_EDIT_TDIR                   1149
#define IDC_CNT_NAME3                   1150
#define IDC_BUTTON_TABSYSMENU           1150
#define IDC_EDIT_RDIR                   1150
#define IDC_CNT_NAME4                   1151
#define IDC_EDIT_ERROR                  1151
#define IDC_CNT_DATA1                   1152
#define IDC_EDIT_DECKTHR                1152
#define IDC_CNT_DATA2                   1153
#define IDC_BUTTON_MOTIONTAB2           1153
#define IDC_LIST_DATADISPLAY            1153
#define IDC_EDIT_PDIST                  1153
#define IDC_CNT_DATA3                   1154
#define IDC_BUTTON_MOTIONTAB3           1154
#define IDC_EDIT_LOC                    1154
#define IDC_CNT_DATA4                   1155
#define IDC_EDIT_BTHR                   1155
#define IDC_BUTTON_MOTIONTAB1           1155
#define IDC_CNT_NAME5                   1156
#define IDC_EDIT_PARA                   1156
#define IDC_BUTTON_MOTIONTAB4           1156
#define IDC_CNT_NAME6                   1157
#define IDC_EDIT_BDISP                  1157
#define IDC_BUTTON_ABCENTER             1157
#define IDC_CNT_NAME7                   1158
#define IDC_EDIT_DIAC                   1158
#define IDC_BUTTON_MANUALOPT            1158
#define IDC_CNT_NAME8                   1159
#define IDC_EDIT_DIAL                   1159
#define IDC_BUTTON_AMOPT                1159
#define IDC_CNT_DATA5                   1160
#define IDC_EDIT_DIAH                   1160
#define IDC_BUTTON_RTOFFSET             1160
#define IDC_CNT_DATA6                   1161
#define IDC_EDIT_TILTC                  1161
#define IDC_CNT_DATA7                   1162
#define IDC_EDIT_TILTL                  1162
#define IDC_CNT_DATA8                   1163
#define IDC_EDIT_TILTH                  1163
#define IDC_EDIT_BSIZE                  1164
#define IDC_CNT_NAME9                   1164
#define IDC_EDIT_BPIXEL                 1165
#define IDC_EDIT_RIMP                   1166
#define IDC_EDIT_PTHR                   1167
#define IDC_EDIT_WIDTHCORRECT           1168
#define IDC_EDIT_DATATHR                1169
#define IDC_EDIT_RIMLOCATE              1170
#define IDC_EDIT_RIMINSPECT             1171
#define IDC_EDIT_OLSIZE                 1172
#define IDC_EDIT_PDATA                  1173
#define IDC_EDIT_WIDTHCORRECT2          1174
#define IDC_EDIT_PDIST2                 1175
#define IDC_EDIT_ERROR2                 1176
#define IDC_EDIT_ERROR3                 1177
#define IDC_EDIT_ERROR4                 1178
#define IDC_EDIT_ERROR5                 1179
#define IDC_EDIT_ERROR6                 1180
#define IDC_ST_ERROR                    1181
#define IDC_ST_BTHR                     1182
#define IDC_ST_ERROR5                   1183
#define IDC_EDIT_ERROR7                 1184
#define IDC_EDIT_ERROR8                 1185
#define IDC_CHECK_LOCATION              1199
#define IDC_CHECK_ANGLE                 1200
#define IDC_BUTTON_SYSMENU_3DMODEL      1200
#define IDC_CHECK_TILT                  1201
#define IDC_SPIN_MINUTE                 1201
#define IDC_ST_MINUTE                   1202
#define IDC_CHECK_RIM                   1202
#define IDC_ST_PIXEL                    1203
#define IDC_CHECK_SIZE                  1203
#define IDC_SPIN_PIXEL                  1204
#define IDC_CHECK_PARALLELISM           1204
#define IDC_ST_DISPTYPE                 1205
#define IDC_CHECK_PEAK                  1205
#define IDC_SPIN_DISPTYPE               1206
#define IDC_ST_TDIR                     1207
#define IDC_SPIN_TDIR                   1208
#define IDC_ST_RDIR                     1209
#define IDC_SPIN_RDIR                   1210
#define IDC_BUTTON_SETUP_APPLY          1211
#define IDC_SPIN_ERROR                  1212
#define IDC_EDIT_3DSET1                 1212
#define IDC_ST_DECKTHR                  1213
#define IDC_SPIN_3DSET1                 1213
#define IDC_SPIN_DECKTHR                1214
#define IDC_ST_3DSET1                   1214
#define IDC_ST_3DSET2                   1215
#define IDC_ST_PDIST                    1215
#define IDC_EDIT_3DSET2                 1216
#define IDC_SPIN_PDIST                  1216
#define IDC_BUTTON_SETUP_SAVE           1217
#define IDC_SPIN_3DSET2                 1217
#define IDC_BUTTON_PASSWD               1218
#define IDC_ST_3DSET3                   1218
#define IDC_EDIT_3DSET3                 1219
#define IDC_ST_LOC                      1219
#define IDC_SPIN_3DSET3                 1220
#define IDC_SPIN_LOC                    1220
#define IDC_ST_3DSET4                   1221
#define IDC_SPIN_BTHR                   1221
#define IDC_EDIT_3DSET4                 1222
#define IDC_ST_PARA                     1222
#define IDC_SPIN_3DSET4                 1223
#define IDC_SPIN_PARA                   1223
#define IDC_ST_3DSET5                   1224
#define IDC_ST_BDISP                    1224
#define IDC_EDIT_3DSET5                 1225
#define IDC_SPIN_BDISP                  1225
#define IDC_SPIN_3DSET5                 1226
#define IDC_ST_DIAMETER                 1226
#define IDC_ST_3DSET6                   1227
#define IDC_SPIN_DIAC                   1227
#define IDC_EDIT_3DSET6                 1228
#define IDC_SPIN_DIAL                   1228
#define IDC_SPIN_3DSET6                 1229
#define IDC_SPIN_DIAH                   1229
#define IDC_ST_3DSET7                   1230
#define IDC_ST_TILT                     1230
#define IDC_EDIT_3DSET7                 1231
#define IDC_SPIN_TILTC                  1231
#define IDC_SPIN_3DSET7                 1232
#define IDC_SPIN_TILTL                  1232
#define IDC_ST_3DSET8                   1233
#define IDC_SPIN_TILTH                  1233
#define IDC_EDIT_3DSET8                 1234
#define IDC_ST_BSIZE                    1234
#define IDC_SPIN_3DSET8                 1235
#define IDC_SPIN_BSIZE                  1235
#define IDC_ST_3DSET9                   1236
#define IDC_ST_BPIXEL                   1236
#define IDC_EDIT_3DSET9                 1237
#define IDC_SPIN_BPIXEL                 1237
#define IDC_SPIN_3DSET9                 1238
#define IDC_ST_RIMP                     1238
#define IDC_ST_3DSET10                  1239
#define IDC_SPIN_RIMP                   1239
#define IDC_EDIT_3DSET10                1240
#define IDC_ST_PTHR                     1240
#define IDC_SPIN_3DSET10                1241
#define IDC_SPIN_PTHR                   1241
#define IDC_ST_3DSET11                  1242
#define IDC_ST_WIDTHCORRECT             1242
#define IDC_EDIT_3DSET11                1243
#define IDC_SPIN_WIDTHCORRECT           1243
#define IDC_SPIN_3DSET11                1244
#define IDC_ST_DATATHR                  1244
#define IDC_ST_3DSET12                  1245
#define IDC_SPIN_DATATHR                1245
#define IDC_EDIT_3DSET12                1246
#define IDC_ST_RIMLOCATE                1246
#define IDC_SPIN_3DSET12                1247
#define IDC_SPIN_RIMLOCATE              1247
#define IDC_ST_3DSET13                  1248
#define IDC_ST_RIMINSPECT               1248
#define IDC_EDIT_3DSET13                1249
#define IDC_SPIN_RIMINSPECT             1249
#define IDC_SPIN_3DSET13                1250
#define IDC_ST_OLSIZE                   1250
#define IDC_3DMODEL_SAVE                1251
#define IDC_SPIN_OLSIZE                 1251
#define IDC_LIST_GNERALDATA1            1252
#define IDC_ST_PDATA                    1252
#define IDC_LIST_PEAKDATA               1253
#define IDC_SPIN_PDATA                  1253
#define IDC_LIST_RIMDATA                1254
#define IDC_CHECK_BUTTON_ALIMIT         1254
#define IDC_LIST_GNERALDATA2            1255
#define IDC_CHECK_BUTTON_DISTANCE       1255
#define IDC_CHECK_BUTTON_PARALLELISM    1256
#define IDC_EDIT_PASSINPUT              1256
#define IDC_CHECK_BUTTON_RIM            1257
#define IDC_EDIT_PASSNEW                1257
#define IDC_CHECK_BUTTON_DIAMETER       1258
#define IDC_EDIT_PASSCONFIRM            1258
#define IDC_CHECK_BUTTON_TILT           1259
#define IDC_CHECK_BUTTON_PDIST          1260
#define IDC_CHECK_BUTTON_RIM2           1261
#define IDC_SPIN_WIDTHCORRECT2          1262
#define IDC_SPIN_PDIST2                 1263
#define IDC_BUTTONUP                    1263
#define IDC_BUTTON_SETUP_DEFAULT        1264
#define IDC_BUTTONCENTER                1264
#define IDC_BUTTONDOWN                  1265
#define IDC_SPIN_ERROR2                 1265
#define IDC_BUTTONRIGHT                 1266
#define IDC_SPIN_ERROR3                 1266
#define IDC_BUTTONLEFT                  1267
#define IDC_SPIN_ERROR4                 1267
#define IDC_BUTTON_SYSMENU_MOVE         1268
#define IDC_SPIN_ERROR5                 1268
#define IDC_STATIC_TAB_ROFFSET          1269
#define IDC_SPIN_ERROR6                 1269
#define IDC_EDIT_TAB_ROFFSET            1270
#define IDC_SPIN_ERROR7                 1270
#define IDC_SPIN_TAB_ROFFSET            1271
#define IDC_SPIN_ERROR8                 1271
#define IDC_STATIC_TAB_TOFFSET          1272
#define IDC_EDIT_TAB_TOFFSET            1273
#define IDC_SPIN_TAB_TOFFSET            1274
#define IDC_STATIC_TAB_FRAME            1275
#define IDC_BUTTON_TAB_ETCSAVE          1276
#define IDC_BUTTON_TAB_ETCAPPLY         1277
#define IDC_STATIC_ETC1                 1278
#define IDC_BUTTON_MASTERMODE           1279
#define IDC_BUTTON_LINK                 1280
#define IDC_EDIT_ETC1                   1280
#define IDC_TITLE_BUTTON1               1281
#define IDC_SPIN_ETC1                   1281
#define IDC_TITLE_BUTTON2               1282
#define IDC_STATIC_ETC2                 1282
#define IDC_EDIT_ETC2                   1283
#define IDC_TITLE_BUTTON3               1283
#define IDC_SPIN_ETC2                   1284
#define IDC_TITLE_BUTTON4               1284
#define IDC_STATIC_ETC3                 1285
#define IDC_EDIT_ETC3                   1286
#define IDC_SPIN_ETC3                   1287
#define IDC_STATIC_ETC4                 1288
#define IDC_EDIT_ETC4                   1289
#define IDC_SPIN_ETC4                   1290
#define IDC_STATIC_ETC5                 1291
#define IDC_EDIT_ETC5                   1292
#define IDC_SPIN_ETC5                   1293
#define IDC_STATIC_ETC6                 1294
#define IDC_EDIT_ETC6                   1295
#define IDC_SPIN_ETC6                   1296
#define IDC_STATIC_ETC7                 1297
#define IDC_EDIT_ETC7                   1298
#define IDC_SPIN_ETC7                   1299
#define IDC_CHECK_ETC_ROI               1300
#define IDC_EDIT_ETC8                   1301
#define IDC_STATIC_BCODE                1301
#define IDC_SPIN_ETC8                   1302
#define IDC_EDIT_BCODE                  1302
#define IDC_STATIC_ETC8                 1303
#define IDC_COMBO1                      1304
#define IDC_STATIC_ETC9                 1305
#define IDC_COMBO2                      1306
#define IDC_TAB_BTN_MOTION              1306
#define IDC_EDIT_ETC9                   1307
#define IDC_TAB_BTN_IO                  1308
#define IDC_SPIN_ETC9                   1308
#define IDC_LABEL_IO                    1309
#define IDC_EDIT_ETC10                  1309
#define IDC_SPIN_ETC10                  1310
#define IDC_STATIC_ETC10                1311
#define IDC_STATIC_SELECT_CAMERA        1312
#define IDC_STATIC_ETC11                1312
#define IDC_STATIC_CAMCTL1              1313
#define IDC_EDIT_ETC11                  1313
#define IDC_STATIC_CAMCTL2              1314
#define IDC_SPIN_ETC11                  1314
#define IDC_STATIC_CAMCTL3              1315
#define IDC_EDIT_ETC12                  1315
#define IDC_STATIC_CAMCTL4              1316
#define IDC_SPIN_ETC12                  1316
#define IDC_STATIC_CAMCTL5              1317
#define IDC_STATIC_ETC12                1317
#define IDC_STATIC_CAMCTLEX1            1318
#define IDC_EDIT_ETC13                  1318
#define IDC_STATIC_CAMCTLEX2            1319
#define IDC_SPIN_ETC13                  1319
#define IDC_STATIC_CAMCTLEX3            1320
#define IDC_EDIT_ETC14                  1320
#define IDC_STATIC_CAMCTLEX4            1321
#define IDC_SPIN_ETC14                  1321
#define IDC_STATIC_CAMCTLEX5            1322
#define IDC_STATIC_ETC13                1322
#define IDC_COMBO_CAMERA                1323
#define IDC_EDIT_ETC15                  1323
#define IDC_EDIT_CAMCTRL1               1324
#define IDC_SPIN_ETC15                  1324
#define IDC_EDIT_CAMCTRL2               1325
#define IDC_EDIT_ETC16                  1325
#define IDC_EDIT_CAMCTRL3               1326
#define IDC_SPIN_ETC16                  1326
#define IDC_EDIT_CAMCTRL4               1327
#define IDC_EDIT_CAMCTRL5               1328
#define IDC_SPIN_CAMCTRL1               1330
#define IDC_SPIN_CAMCTRL2               1331
#define IDC_SPIN_CAMCTRL3               1332
#define IDC_SPIN_CAMCTRL4               1333
#define IDC_SPIN_CAMCTRL5               1334
#define IDC_BUTTON_SETDEFAULT1          1335
#define IDC_BUTTON_SETDEFAULT2          1336
#define IDC_BTN_UI_SHOW                 1336
#define IDC_LABEL_INPUT1                1337
#define IDC_BUTTON_SETDEFAULT3          1337
#define IDC_BTN_ALL_HOME                1337
#define IDC_LABEL_INPUT2                1338
#define IDC_BUTTON_SETDEFAULT4          1338
#define IDC_BTN_RESET                   1338
#define IDC_LABEL_INPUT3                1339
#define IDC_BUTTON_SETDEFAULT5          1339
#define IDC_BTN_APC_LEFT                1339
#define IDC_LABEL_INPUT4                1340
#define IDC_BTN_APC_RIGHT               1340
#define IDC_LABEL_INPUT5                1341
#define IDC_BTN_APC_UP                  1341
#define IDC_LABEL_INPUT6                1342
#define IDC_BTN_APC_DOWN                1342
#define IDC_LABEL_INPUT7                1343
#define IDC_LABEL_INPUT8                1344
#define IDC_LABEL_INPUT9                1345
#define IDC_LABEL_INPUT10               1346
#define IDC_LABEL_INPUT11               1347
#define IDC_LABEL_INPUT12               1348
#define IDC_LABEL_INPUT13               1349
#define IDC_LABEL_INPUT14               1350
#define IDC_LABEL_INPUT15               1351
#define IDC_LABEL_INPUT0                1352
#define IDC_LABEL_OUTPUT15              1353
#define IDC_LABEL_OUTPUT1               1354
#define IDC_LABEL_OUTPUT2               1355
#define IDC_LABEL_OUTPUT3               1356
#define IDC_LABEL_OUTPUT4               1357
#define IDC_LABEL_OUTPUT5               1358
#define IDC_LABEL_OUTPUT6               1359
#define IDC_LABEL_OUTPUT7               1360
#define IDC_LABEL_OUTPUT8               1361
#define IDC_LABEL_OUTPUT9               1362
#define IDC_LABEL_OUTPUT10              1363
#define IDC_LABEL_OUTPUT11              1364
#define IDC_LABEL_OUTPUT12              1365
#define IDC_LABEL_OUTPUT13              1366
#define IDC_LABEL_OUTPUT14              1367
#define IDC_LABEL_OUTPUT0               1368

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        496
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1341
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
