//---------------------------------------------------------------------------
#ifndef FormOperationH
#define FormOperationH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <Buttons.hpp>
//---------------------------------------------------------------------------
//#include "FormPassword.h"
#include <Graphics.hpp>
#include <ComCtrls.hpp>
#include <Grids.hpp>
#include <jpeg.hpp>
#include "CSPIN.h"
#include <Dialogs.hpp>
//---------------------------------------------------------------------------
#include "FrameMotr.h"
class TFrmOperation : public TForm
{
__published:	// IDE-managed Components
    TPanel *Panel1;
    TPanel *Panel6;
    TPanel *Panel7;
    TBitBtn *btStart;
    TBitBtn *btStop;
    TBitBtn *btReset;
    TBitBtn *btOperator;
    TTimer *tmUpdate;
    TPanel *pnVisn;
    TPanel *pnControl;
    TPanel *Panel8;
    TLabel *lbDInfo0;
    TLabel *lbDInfo1;
    TLabel *lbDInfo2;
    TLabel *lbDInfo3;
    TLabel *lbDInfo4;
    TLabel *lbDInfo5;
    TLabel *lbDInfo7;
    TLabel *lbDInfo6;
    TPanel *Panel9;
    TPanel *pnDayRunTime;
    TPanel *pnDayIdleTime;
    TPanel *pnDayJamTime;
    TPanel *pnDayTotalTime;
        TPanel *pnDayChipUph;
    TPanel *pnDayWorkChip;
    TPanel *pnDayLotCount;
    TPanel *pnDayFailChip;
    TPanel *Panel2;
    TLabel *lbLInfo0;
    TLabel *lbLInfo2;
    TLabel *lbLInfo4;
    TLabel *lbLInfo5;
    TLabel *lbLInfo6;
    TLabel *lbLInfo3;
    TLabel *lbLInfo1;
    TPanel *Panel11;
    TPanel *pnLotNo;
    TPanel *pnLotWorkChip;
        TPanel *pnLotChipUph;
    TPanel *pnLotStartTime;
    TPanel *pnLotRunTime;
    TPanel *pnLotFailChip;
    TPanel *pnLotJobFile;
    TPanel *Panel12;
    TPanel *Panel13;
    TPanel *Panel32;
    TLabel *lbOption0;
        TPanel *pnOptn1;
    TPanel *Panel4;
    TLabel *lbOption3;
    TPanel *pnOptn3;
    TPanel *Panel34;
    TLabel *lbOption4;
    TPanel *pnOptn4;
    TPanel *Panel22;
    TLabel *lbOption7;
    TPanel *pnOptn7;
    TPanel *Panel25;
    TLabel *lbOption2;
    TPanel *pnOptn2;
    TPanel *Panel23;
    TLabel *lbOption1;
        TPanel *pnOptn0;
    TPanel *Panel21;
    TLabel *lbOption5;
    TPanel *pnOptn5;
    TPanel *Panel17;
    TLabel *lbOption6;
    TPanel *pnOptn6;
    TPanel *Panel14;
    TPanel *Panel15;
    TListBox *lbErr;
    TPanel *Panel16;
    TPanel *Panel18;
    TBitBtn *btLotOpen;
    TBitBtn *btLotEnd;
        TPanel *pnManual;
    TPanel *Panel20;
    TPageControl *pcManual;
    TTabSheet *TabSheet1;
    TBitBtn *btMan1_1;
    TBitBtn *btMan1_2;
    TBitBtn *btMan1_7;
    TBitBtn *btMan1_3;
    TBitBtn *btMan1_4;
    TBitBtn *btMan1_5;
    TBitBtn *btMan1_6;
    TBitBtn *btMan1_8;
    TBitBtn *btMan1_9;
    TBitBtn *btMan1_A;
    TBitBtn *btMan1_B;
    TBitBtn *btMan1_C;
    TBitBtn *btMan1_D;
    TBitBtn *btMan1_E;
    TTabSheet *TabSheet2;
    TTabSheet *TabSheet3;
    TTabSheet *TabSheet4;
    TTabSheet *TabSheet11;
    TTabSheet *TabSheet12;
    TPageControl *pcControl;
    TTabSheet *TabSheet9;
    TPanel *Panel24;
    TTabSheet *TabSheet10;
    TPanel *Panel26;
        TTabSheet *tbMapFile;
    TPanel *plPassWord;
    TPanel *Panel19;
    TLabel *Label17;
    TBitBtn *btPasswordClose;
    TBitBtn *btEngr;
    TBitBtn *btOper;
    TBitBtn *btMast;
    TPanel *pnTVisn;
    TPanel *pnTControl;
    TTabSheet *TabSheet13;
    TBitBtn *btMan2_1;
    TBitBtn *btMan2_2;
    TBitBtn *btMan2_7;
    TBitBtn *btMan2_3;
    TBitBtn *btMan2_4;
    TBitBtn *btMan2_5;
    TBitBtn *btMan2_6;
    TBitBtn *btMan2_8;
    TBitBtn *btMan2_9;
    TBitBtn *btMan2_A;
    TBitBtn *btMan2_B;
    TBitBtn *btMan2_C;
    TBitBtn *btMan2_D;
    TBitBtn *btMan2_E;
    TBitBtn *btMan3_1;
    TBitBtn *btMan3_2;
    TBitBtn *btMan3_7;
    TBitBtn *btMan3_3;
    TBitBtn *btMan3_4;
    TBitBtn *btMan3_5;
    TBitBtn *btMan3_6;
    TBitBtn *btMan3_8;
    TBitBtn *btMan3_9;
    TBitBtn *btMan3_A;
    TBitBtn *btMan3_B;
    TBitBtn *btMan3_C;
    TBitBtn *btMan3_D;
    TBitBtn *btMan3_E;
    TBitBtn *btMan4_1;
    TBitBtn *btMan4_2;
    TBitBtn *btMan4_7;
    TBitBtn *btMan4_3;
    TBitBtn *btMan4_4;
    TBitBtn *btMan4_5;
    TBitBtn *btMan4_6;
    TBitBtn *btMan4_8;
    TBitBtn *btMan4_9;
    TBitBtn *btMan4_A;
    TBitBtn *btMan4_B;
    TBitBtn *btMan4_C;
    TBitBtn *btMan4_D;
    TBitBtn *btMan4_E;
    TBitBtn *btMan5_1;
    TBitBtn *btMan5_2;
    TBitBtn *btMan5_7;
    TBitBtn *btMan5_3;
    TBitBtn *btMan5_4;
    TBitBtn *btMan5_5;
    TBitBtn *btMan5_6;
    TBitBtn *btMan5_8;
    TBitBtn *btMan5_9;
    TBitBtn *btMan5_A;
    TBitBtn *btMan5_B;
    TBitBtn *btMan5_C;
    TBitBtn *btMan5_D;
    TBitBtn *btMan5_E;
    TBitBtn *btMan6_1;
    TBitBtn *btMan6_2;
    TBitBtn *btMan6_7;
    TBitBtn *btMan6_3;
    TBitBtn *btMan6_4;
    TBitBtn *btMan6_5;
    TBitBtn *btMan6_6;
    TBitBtn *btMan6_8;
    TBitBtn *btMan6_9;
    TBitBtn *btMan6_A;
    TBitBtn *btMan6_B;
    TBitBtn *btMan6_C;
    TBitBtn *btMan6_D;
    TBitBtn *btMan6_E;
    TBitBtn *btMan7_1;
    TBitBtn *btMan7_2;
    TBitBtn *btMan7_7;
    TBitBtn *btMan7_3;
    TBitBtn *btMan7_4;
    TBitBtn *btMan7_5;
    TBitBtn *btMan7_6;
    TBitBtn *btMan7_8;
    TBitBtn *btMan7_9;
    TBitBtn *btMan7_A;
    TBitBtn *btMan7_B;
    TBitBtn *btMan7_C;
    TBitBtn *btMan7_D;
    TBitBtn *btMan7_E;
    TPanel *pnVisnBase;
    TTabSheet *tsSetup;
    TPanel *Panel27;
    TPanel *Panel10;
    TPanel *pnLDR;
    TPanel *Panel28;
    TPanel *Panel29;
    TPanel *pnPRB;
    TPanel *Panel30;
    TPanel *Panel31;
    TPanel *pnULD;
    TPanel *Panel33;
    TPanel *Panel35;
    TPanel *Panel36;
    TPanel *Panel37;
    TPanel *Panel38;
    TPanel *Panel39;
    TPanel *Panel40;
    TPanel *Panel41;
        TPanel *pnWafer;
    TPanel *Panel44;
    TPanel *Panel45;
    TPanel *Panel47;
    TPanel *Panel48;
    TPanel *pnSTG;
    TPanel *pnHED;
    TPanel *pnCST;
        TPageControl *pcWRE;
        TTabSheet *TabSheet5;
        TTabSheet *TabSheet6;
    TPanel *pnREV;
        TPageControl *pcWRD;
        TTabSheet *TabSheet7;
        TTabSheet *TabSheet8;
        TPageControl *pcPSB;
        TTabSheet *TabSheet15;
        TTabSheet *TabSheet16;
    TPanel *pnRDV;
    TPanel *pnPSV;
    TPanel *pnREF;
    TPanel *pnRDF;
    TPanel *pnPSF;
    TPageControl *pcMap;
    TTabSheet *TabSheet17;
    TLabel *Label18;
    TLabel *Label22;
    TLabel *Label27;
    TLabel *Label28;
    TLabel *Label29;
    TLabel *Label30;
    TLabel *lbLotNo1;
    TLabel *lbLotNo2;
    TLabel *lbLotNo3;
    TLabel *lbLotNo4;
    TLabel *lbLotNo5;
    TLabel *lbLotNo6;
    TLabel *lbId1;
    TLabel *lbId2;
    TLabel *lbId3;
    TLabel *lbId4;
    TLabel *lbId5;
    TLabel *lbId6;
    TButton *Button8;
        TRadioGroup *rgJogUnit;
        TGroupBox *GroupBox2;
        TPanel *Panel49;
        TBitBtn *btHed_ZUp;
        TBitBtn *btHed_ZDn;
        TGroupBox *GroupBox3;
        TPanel *Panel50;
        TBitBtn *btSTG_TUc;
        TBitBtn *btSTG_Tcl;
        TGroupBox *GroupBox4;
        TPanel *Panel51;
        TBitBtn *btWRD_YUp;
        TBitBtn *btWRD_YDn;
        TGroupBox *GroupBox20;
        TPanel *pnHED_X;
        TBitBtn *btHED_XRt;
        TBitBtn *btHED_YDn;
        TBitBtn *btHED_XLt;
        TBitBtn *btHED_YUp;
        TGroupBox *GroupBox1;
        TPanel *Panel3;
        TBitBtn *btSTG_XRt;
        TBitBtn *btSTG_YDn;
        TBitBtn *btSTG_XLt;
        TBitBtn *btSTG_YUp;
        TEdit *edJogUnit;
        TLabel *lb1;
        TLabel *lb2;
        TLabel *lb3;
        TButton *btSetDirctionRight;
        TLabel *Label11;
        TPanel *pnPickCycleTime;
    TButton *btChipAlign;
        TPanel *Panel52;
        TBitBtn *btDieVauum;
        TStaticText *StaticText6;
        TPanel *Panel62;
        TBitBtn *btEjtVacuum;
        TStaticText *StaticText3;
        TButton *Button16;
        TTimer *tmUpdateAray;
        TButton *btSetDirctionLeft;
    TBitBtn *btEPXPass;
    TButton *Button22;
    TBitBtn *btStopStg;
    TBitBtn *btStopHed;
        TBitBtn *btSave;
        TBitBtn *btOpen;
        TOpenDialog *OpenDialog1;
        TSaveDialog *SaveDialog1;
        TBitBtn *btOriPass;
        TLabel *Label7;
        TLabel *lbEpxCnt;
        TButton *btEpxSet;
        TEdit *edEpxSet;
        TButton *Button10;
        TLabel *Label12;
        TPanel *pnLotChipUpeh;
        TLabel *Label31;
        TPanel *pnDayChipUpeh;
        TPanel *Panel63;
        TPanel *Panel64;
        TStaticText *StaticText7;
        TStaticText *lbGoodCntWf;
        TStaticText *StaticText10;
        TStaticText *lbFailCntWf;
        TStaticText *StaticText12;
    TStaticText *lbEmptyCntWf;
    TBitBtn *btPrbSkip;
    TBitBtn *btWreSkip;
    TBitBtn *btWrdSkip;
        TBitBtn *btPrbClear;
        TBitBtn *btEpxClear;
        TBitBtn *btDieClear;
        TBitBtn *btPsbClear;
        TButton *Button20;
        TButton *Button21;
        TBitBtn *BitBtn1;
        TButton *Button15;
        TPanel *Panel58;
        TStringGrid *sgOutput1;
        TPanel *Panel59;
        TPanel *Panel60;
        TPanel *Panel61;
        TStaticText *StaticText9;
        TStaticText *lbGoodCnt;
        TStaticText *StaticText2;
        TStaticText *lbFailCnt;
        TStaticText *StaticText4;
        TStaticText *lbNoneCnt;
        TStaticText *StaticText1;
        TStaticText *lbFstCol;
        TStaticText *StaticText5;
        TStaticText *lbFstRow;
        TPanel *Panel43;
        TPanel *Panel46;
        TLabel *Label1;
        TPanel *pnMAP;
        TLabel *Label2;
        TButton *Button26;
        TButton *btSourceFolder;
        TButton *btWorkedFolder;
        TMemo *mmMemo;
        TLabel *Label3;
        TLabel *Label4;
        TLabel *Label5;
        TLabel *Label6;
        TLabel *Label8;
        TPanel *Panel5;
    void __fastcall FormShow(TObject *Sender);
    void __fastcall btOperatorClick(TObject *Sender);
    void __fastcall btPasswordCloseClick(TObject *Sender);
    void __fastcall btOperClick(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
        void __fastcall btStopClick(TObject *Sender);
        void __fastcall btResetClick(TObject *Sender);
    void __fastcall btMan1_1Click(TObject *Sender);
    void __fastcall btStartClick(TObject *Sender);
    void __fastcall FormDestroy(TObject *Sender);
    void __fastcall pnOptn1Click(TObject *Sender);
    void __fastcall edJogUnitChange(TObject *Sender);
    void __fastcall btSourceClick(TObject *Sender);
    void __fastcall btOutputClick(TObject *Sender);
    void __fastcall sgOutput1Click(TObject *Sender);
    void __fastcall btLotOpenClick(TObject *Sender);
    void __fastcall btLotEndClick(TObject *Sender);
    void __fastcall Button8Click(TObject *Sender);
    void __fastcall rgJogUnitClick(TObject *Sender);
        void __fastcall btSetDirctionRightClick(TObject *Sender);
        void __fastcall btJogNMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btJogNMouseUp(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
        void __fastcall btJogPMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btJogPMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall tmUpdateTimer(TObject *Sender);
    void __fastcall btChipAlignClick(TObject *Sender);
        void __fastcall btEjtVacuumClick(TObject *Sender);
        void __fastcall Button16Click(TObject *Sender);
        void __fastcall tmUpdateArayTimer(TObject *Sender);
        void __fastcall Button20Click(TObject *Sender);
        void __fastcall Button21Click(TObject *Sender);
    void __fastcall btEPXPassClick(TObject *Sender);
    void __fastcall Button22Click(TObject *Sender);
    void __fastcall btStopStgClick(TObject *Sender);
    void __fastcall btStopHedClick(TObject *Sender);
        void __fastcall btSaveClick(TObject *Sender);
        void __fastcall btOpenClick(TObject *Sender);
        void __fastcall btOriPassClick(TObject *Sender);
    void __fastcall btPrbSkipClick(TObject *Sender);
        void __fastcall btPrbClearClick(TObject *Sender);
        void __fastcall BitBtn1Click(TObject *Sender);
        void __fastcall Button15Click(TObject *Sender);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall Button26Click(TObject *Sender);
        void __fastcall btSourceFolderClick(TObject *Sender);
        void __fastcall pcControlChange(TObject *Sender);
        void __fastcall btWorkedFolderClick(TObject *Sender);
        void __fastcall Panel15Click(TObject *Sender);

private:	// User declarations
    double dUnit    ;
    double dPitch   ;
    int    iUnitType;

    void DM_Init   (); //Data Man Init.
    void Man_Init  (); //Manual Button , Tag Init.
    void LT_Display(); //Lot Display
    void OP_Dispaly(); //Option Display
    void LV_Display(); //Level Display
    void ER_Display(); //Err List Display.
    void __fastcall SetManualBtn(TBitBtn *_btn , String _sCaption , int _iTag) ;

    void SetUnitInit();
    void SetPitch(double _dUnit);
    void SetUnit(EN_UNIT_TYPE _iUnitType , double _dUnit);

    void UpdateAray();




public:		// User declarations
    __fastcall TFrmOperation(TComponent* Owner);
    bool __fastcall CheckStripDisappear();
    bool __fastcall CheckStripUnknwon  ();
    AnsiString sOutName;
    int iTemp;
};
//---------------------------------------------------------------------------
extern PACKAGE TFrmOperation *FrmOperation;
//---------------------------------------------------------------------------
#endif
