//---------------------------------------------------------------------------

#ifndef FormDeviceSetH
#define FormDeviceSetH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Buttons.hpp>
#include <jpeg.hpp>
#include <Grids.hpp>
//---------------------------------------------------------------------------
#include "Timer.h"
#include "FrameMotr.h"
#include "FrameCyl.h"
#include <ImgList.hpp>
class TFrmDeviceSet : public TForm
{
__published:	// IDE-managed Components
    TTimer *tmUpdateTimer;
        TImageList *ImageList1;
        TPageControl *pcDeviceSet;
        TTabSheet *tsDeviceInfo;
        TGroupBox *GroupBox10;
        TImage *Image2;
        TLabel *Label10;
        TLabel *Label11;
        TLabel *Label12;
        TLabel *Label13;
        TStaticText *lbRowPitch;
        TEdit *edRowPitch;
        TStaticText *lbColPitch;
        TEdit *edColPitch;
        TStaticText *lbRowGroupCount;
        TEdit *edRowGroupCount;
        TStaticText *lbColCount;
        TEdit *edColCount;
        TStaticText *lbRowGroupGap;
        TEdit *edRowGroupGap;
        TStaticText *lbColGroupGap;
        TEdit *edColGroupGap;
        TStaticText *lbRowCount;
        TEdit *edRowCount;
        TStaticText *lbSrColCntrPitch;
        TEdit *edColGroupCount;
        TGroupBox *GroupBox11;
        TImage *Image3;
        TStaticText *StaticText8;
        TEdit *edCsSlotCnt;
        TStaticText *StaticText10;
        TEdit *edCsSlotPitch;
        TTabSheet *TabSheet3;
        TImage *Image7;
        TGroupBox *GroupBox1;
        TPanel *pnLd1Z;
        TGroupBox *GroupBox23;
        TPanel *pnLd1Y;
        TPanel *Panel6;
        TRadioGroup *rgLDRJogUnit;
        TEdit *edLDRJogUnit;
        TPageControl *PageControl3;
        TTabSheet *TabSheet8;
        TTabSheet *tsPosition;
        TGroupBox *GroupBox5;
        TPanel *pnRl1X;
        TGroupBox *GroupBox6;
    TPanel *pnRl2X;
        TGroupBox *GroupBox24;
        TPanel *pnRl3X;
        TPanel *Panel1;
        TPageControl *PageControl1;
        TTabSheet *TabSheet2;
        TRadioGroup *rgRALJogUnit;
        TEdit *edRALJogUnit;
        TTabSheet *TabSheet4;
        TGroupBox *GroupBox7;
        TPanel *pnPbT;
        TGroupBox *GroupBox8;
    TPanel *pnPbBZ;
        TButton *btInspStart;
        TButton *btToolChange;
        TButton *btCntctRpt;
        TButton *btResetRpt;
        TStringGrid *sgProbeCrnt;
        TPanel *pnProbeMotr;
        TPanel *Panel2;
        TPageControl *PageControl2;
        TTabSheet *TabSheet6;
        TRadioGroup *rgWRKJogUnit;
        TEdit *edWRKJogUnit;
        TTabSheet *TabSheet1;
        TGroupBox *GroupBox29;
        TPanel *pnSTLYT;
        TGroupBox *GroupBox30;
        TPanel *pnSTLYB;
        TGroupBox *GroupBox32;
        TPanel *pnREJXB;
        TPanel *Panel31;
        TRadioGroup *rgSTLJogUnit;
        TEdit *edSTLJogUnit;
        TPageControl *PageControl5;
        TTabSheet *TabSheet11;
        TTabSheet *TabSheet7;
        TImage *Image9;
        TGroupBox *GroupBox25;
        TPanel *pnULDY;
        TGroupBox *GroupBox26;
        TPanel *pnULDZ;
        TPanel *Panel26;
        TRadioGroup *rgULDJogUnit;
        TEdit *edULDJogUnit;
        TPageControl *PageControl4;
        TTabSheet *TabSheet10;
        TBitBtn *btSaveDevice;
        TTabSheet *TabSheet12;
        TPageControl *PageControl6;
        TTabSheet *TabSheet13;
        TTabSheet *TabSheet14;
        TPanel *Panel9;
        TLabel *Label9;
        TLabel *Label14;
        TLabel *Label27;
        TLabel *Label28;
        TPanel *Panel12;
        TImage *Image6;
        TLabel *Label32;
        TEdit *edLotEndMgzCnt;
        TEdit *edWaitDelay;
        TPanel *Panel16;
        TLabel *Label29;
        TLabel *Label33;
        TLabel *Label34;
        TLabel *Label35;
        TPanel *Panel17;
        TImage *Image5;
        TLabel *Label36;
        TEdit *edPreRailOutVel;
        TEdit *edPostRailOutVel;
        TPanel *Panel24;
        TLabel *Label39;
        TLabel *Label40;
        TPanel *Panel25;
        TImage *Image10;
        TLabel *Label38;
        TEdit *edREJPitch;
        TPanel *Panel18;
        TImage *Image11;
        TPanel *Panel23;
        TImage *Image8;
        TLabel *Label42;
        TCheckBox *cbLtHeaterNum2;
        TCheckBox *cbLtHeaterNum3;
        TCheckBox *cbRtHeaterNum2;
        TCheckBox *cbRtHeaterNum3;
        TGroupBox *gbPinSetting;
        TStaticText *StaticText6;
        TStaticText *StaticText7;
        TComboBox *cb2Ch1P;
        TStaticText *StaticText12;
        TStaticText *StaticText9;
        TComboBox *cb2Ch1N;
        TComboBox *cb1Ch1P;
        TComboBox *cb1Ch1N;
        TComboBox *cb2Ch2P;
        TStaticText *StaticText32;
        TStaticText *StaticText33;
        TComboBox *cb2Ch2N;
        TComboBox *cb1Ch2P;
        TComboBox *cb1Ch2N;
        TComboBox *cb2Ch3P;
        TStaticText *StaticText34;
        TStaticText *StaticText35;
        TComboBox *cb2Ch3N;
        TComboBox *cb1Ch3P;
        TComboBox *cb1Ch3N;
        TImage *Image4;
        TImage *Image1;
        TGroupBox *GroupBox16;
        TEdit *edZennerHigh;
        TEdit *edZennerLow;
        TEdit *ed1ChLow;
        TEdit *ed1ChHigh;
        TStaticText *StaticText11;
        TStaticText *StaticText14;
        TEdit *ed2ChLow;
        TEdit *ed2ChHigh;
        TStaticText *StaticText19;
        TStaticText *StaticText20;
        TStaticText *StaticText21;
        TCheckBox *cbUseZenner;
        TGroupBox *GroupBox17;
        TLabel *Label19;
        TLabel *Label20;
        TLabel *Label23;
        TLabel *Label24;
        TLabel *Label25;
        TLabel *Label26;
        TStaticText *StaticText39;
        TEdit *ed1ChDelay;
        TStaticText *StaticText40;
        TEdit *ed1ChLedTime;
        TStaticText *StaticText41;
        TEdit *ed1ChZenTime;
        TStaticText *StaticText42;
        TEdit *ed2ChDelay;
        TStaticText *StaticText43;
        TEdit *ed2ChLedTime;
        TStaticText *StaticText44;
        TEdit *ed2ChZenTime;
        TGroupBox *GroupBox14;
        TLabel *Label5;
        TLabel *Label3;
        TLabel *Label4;
        TLabel *Label8;
        TLabel *Label37;
        TEdit *edContactCnt;
        TStaticText *StaticText22;
        TEdit *edReGrabCnt1;
        TStaticText *StaticText26;
        TEdit *edReGrabCnt2;
        TStaticText *StaticText28;
        TStaticText *StaticText1;
        TEdit *edReInspCnt;
        TEdit *edReGrabPs1;
        TStaticText *StaticText30;
        TEdit *edReGrabPs2;
        TStaticText *StaticText31;
        TStaticText *StaticText36;
        TEdit *edLimInsFailCnt;
        TEdit *edPinCnt;
        TStaticText *StaticText29;
        TEdit *edPrbSttDelay;
        TStaticText *StaticText38;
    TButton *btAutoCal1;
    TButton *btAutoCal2;
        TGroupBox *gbProbeTest;
        TLabel *Label15;
        TLabel *Label16;
        TEdit *edProbeTime;
        TBitBtn *btStartTest;
        TBitBtn *btStopTest;
        TEdit *edPinNumber;
        TMemo *mmProbeTest;
    TPanel *Panel14;
    TLabel *Label49;
    TLabel *Label50;
    TLabel *Label51;
    TLabel *Label52;
    TPanel *Panel15;
    TImage *Image12;
    TLabel *Label57;
    TEdit *edPSBReGripCol;
    TEdit *edPSBReGripOfs;
    TButton *btPSBAutoCAL;
    TImage *Image13;
    TImage *Image14;
    TGroupBox *gbDaegyeom;
    TLabel *Label46;
    TStaticText *lbSwitchingDly;
    TEdit *edSwitchingDly;
    TLabel *lbTrimPtchOfs;
    TLabel *Label62;
    TEdit *edTrimPtchOfs;
    TStaticText *stWorkptchOfs;
    TEdit *edWorkPtchOfs;
    TLabel *Label61;
        TLabel *Label63;
        TLabel *Label64;
        TEdit *edTrimRjtDly;
        TLabel *Label65;
        TLabel *Label66;
        TEdit *edTrimSnrDly;
        TGroupBox *gbProbeComTest;
        TButton *btPbSet;
        TButton *btPbStart;
        TButton *btPbOpen;
        TButton *btPbClose;
        TCheckBox *cbChRvsCrnt;
        TCheckBox *cbUseTwiceInsp;
    TStaticText *StaticText13;
    TEdit *ed1ChLedCur;
    TEdit *ed2ChLedCur;
    TLabel *Label6;
    TLabel *Label7;
    TStaticText *StaticText37;
    TEdit *ed1ChZenCur;
    TEdit *ed2ChZenCur;
        TGroupBox *GroupBox15;
        TStaticText *StaticText15;
        TEdit *edContactPinCnt;
        TBitBtn *brContactCntReset;
        TStaticText *StaticText54;
        TEdit *edLimContactPinCnt;
    TPanel *Panel39;
    TBitBtn *btPSB_SrtTFw;
    TBitBtn *btPSB_SrtTBw;
    TStaticText *StaticText55;
    TPanel *Panel40;
    TBitBtn *btPSB_SrtBFw;
    TBitBtn *btPSB_SrtBBw;
    TStaticText *StaticText58;
        TStaticText *StaticText47;
        TEdit *edDgChipCnt;
        TLabel *Label58;
        TGroupBox *GroupBox19;
        TPanel *pnRl4X;
        TPageControl *PageControl7;
        TTabSheet *TabButton1;
        TTabSheet *TabButton2;
        TGroupBox *GroupBox9;
    TPanel *pnPbBY;
    TGroupBox *GroupBox21;
    TPanel *pnLDR_Y;
    TGroupBox *GroupBox22;
    TPanel *pnLDR_Z;
    TPageControl *PageControl8;
    TTabSheet *TabSheet5;
    TTabSheet *TabSheet9;
    TGroupBox *GroupBox63;
    TPanel *pnLDR_Cmp2;
    TGroupBox *GroupBox39;
    TPanel *pnLDR_Psh2;
    TGroupBox *GroupBox31;
    TPanel *pnLDR_Cmp1;
    TGroupBox *GroupBox40;
    TPanel *pnLDR_Psh1;
    TPageControl *PageControl9;
    TTabSheet *TabSheet15;
    TTabSheet *TabSheet16;
    TPageControl *PageControl10;
    TTabSheet *TabSheet17;
    TTabSheet *TabSheet18;
    TPageControl *PageControl11;
    TTabSheet *TabSheet19;
    TTabSheet *TabSheet20;
    TGroupBox *GroupBox2;
    TPanel *pnRAl_X1;
    TGroupBox *GroupBox3;
    TPanel *pnRAl_X2;
    TGroupBox *GroupBox4;
    TPanel *pnRAl_X3;
    TGroupBox *GroupBox12;
    TPanel *pnRAl_X4;
    TGroupBox *GroupBox13;
    TPanel *pnPRB_ZTop;
    TGroupBox *GroupBox18;
    TPanel *pnPRB_YTop;
    TGroupBox *GroupBox20;
    TPanel *pnPRB_ZBot;
    TGroupBox *GroupBox27;
    TPanel *pnRJT_XBot;
    TGroupBox *GroupBox28;
    TPanel *pnSTR_YTop;
    TGroupBox *GroupBox33;
    TPanel *pnSTR_YBot;
    TGroupBox *GroupBox34;
    TPanel *pnULD_Y;
    TGroupBox *GroupBox35;
    TPanel *pnULD_Z;
    TGroupBox *GroupBox43;
    TPanel *pnPSB_Psh1;
    TGroupBox *GroupBox44;
    TPanel *pnPSB_Cmp1;
    TGroupBox *GroupBox45;
    TPanel *pnWRK_Cmp1;
    TGroupBox *GroupBox46;
    TPanel *pnPRB_IdC1;
    TGroupBox *GroupBox47;
    TPanel *pnPRB_Cmp1;
    TGroupBox *GroupBox36;
    TPanel *pnPRB_Cmp2;
    TGroupBox *GroupBox37;
    TPanel *pnPRB_IdC2;
    TGroupBox *GroupBox38;
    TPanel *pnWRK_Cmp2;
    TGroupBox *GroupBox41;
    TPanel *pnPSB_Cmp2;
    TGroupBox *GroupBox42;
    TPanel *pnPSB_Psh2;
    TGroupBox *GroupBox48;
    TPanel *pnULD_Cmp1;
    TGroupBox *GroupBox49;
    TPanel *pnULD_Cmp2;
    TGroupBox *GroupBox50;
    TPanel *pnSTR_Top1;
    TGroupBox *GroupBox51;
    TPanel *pnSTR_Bot1;
    TGroupBox *GroupBox52;
    TPanel *pnSTR_Top2;
    TGroupBox *GroupBox53;
    TPanel *pnSTR_Bot2;
    void __fastcall btSavePosClick(TObject *Sender);
    void __fastcall tmUpdateTimerTimer(TObject *Sender);
    void __fastcall FormDestroy(TObject *Sender);
    void __fastcall FormShow(TObject *Sender);
    void __fastcall btMtFwDn(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall btMtUp(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall btMtBwDn(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
        void __fastcall pcDeviceSetChange(TObject *Sender);
        void __fastcall btLDR_CmpUpClick(TObject *Sender);
        void __fastcall btLDR_CmpDnClick(TObject *Sender);
    void __fastcall btStartTestClick(TObject *Sender);
        void __fastcall mmProbeTestDblClick(TObject *Sender);
        void __fastcall btToolChangeClick(TObject *Sender);
        void __fastcall btResetRptClick(TObject *Sender);
        void __fastcall btCntctRptClick(TObject *Sender);
        void __fastcall btAutoCal1Click(TObject *Sender);
        void __fastcall btAutoCal2Click(TObject *Sender);
    void __fastcall btLDR_InClick(TObject *Sender);
    void __fastcall btInspStartClick(TObject *Sender);
    void __fastcall btStopTestClick(TObject *Sender);
    void __fastcall btPSBAutoCALClick(TObject *Sender);
        void __fastcall brContactCntResetClick(TObject *Sender);
    void __fastcall btPSB_SrtTFwClick(TObject *Sender);
private:	// User declarations
    //Active Radio Button Page.
    TRadioGroup  * rgUnitUser ;
    TEdit        * edUnitUser ;
    CDelayTimer    m_tmProbeTest ;
public:		// User declarations
    TFraMotr *FraMotor   [MAX_MOTR];
    TFraCyl  *FraCylinder[MAX_ACTR];   

    __fastcall TFrmDeviceSet(TComponent* Owner);
    void __fastcall UpdateDevInfo(bool bTo);
    void __fastcall UpdateDevOptn(bool bTo);
};
//---------------------------------------------------------------------------
extern PACKAGE TFrmDeviceSet *FrmDeviceSet;
//---------------------------------------------------------------------------
#endif
