//---------------------------------------------------------------------------

#ifndef FrmMotorPosH
#define FrmMotorPosH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <Buttons.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include "UtilDefine.h"
//---------------------------------------------------------------------------
class TFormMotorPos : public TForm
{
__published:	// IDE-managed Components
    TPageControl *PageControl;
    TTabSheet *TabSheet1;
    TTabSheet *TabSheet2;
    TTabSheet *TabSheet3;
    TTabSheet *TabSheet4;
    TTabSheet *TabSheet6;
    TGroupBox *GroupBox7;
    TLabel *Label47;
    TLabel *Label48;
        TLabel *lbCmdPos_ZLdr;
        TLabel *lbActPos_ZLdr;
    TLabel *Label51;
    TUpDown *UpDown6;
        TEdit *edMTPosJog1;
    TBitBtn *BitBtn49;
        TBitBtn *BtLDR_CmpUp;
        TBitBtn *BtLDR_CmpDn;
        TPanel *pnLDR_CmpUp;
        TPanel *pnLDR_CmpDn;
    TGroupBox *GroupBox8;
    TLabel *Label57;
    TLabel *Label58;
        TLabel *lbCmdPos_YLdr;
        TLabel *lbActPos_YLdr;
    TLabel *Label61;
    TUpDown *UpDown7;
        TEdit *edMTPosJog0;
    TBitBtn *BitBtn56;
        TBitBtn *BtLDR_PshFw;
        TBitBtn *BtLDR_PshBw;
        TPanel *pnLDR_PshFw;
        TPanel *pnLDR_PshBw;
    TGroupBox *GroupBox9;
    TLabel *Label75;
    TLabel *Label76;
        TLabel *lbCmdPos_ZUld;
        TLabel *lbActPos_ZUld;
    TLabel *Label79;
    TUpDown *UpDown8;
        TEdit *edMTPosJog9;
    TBitBtn *BitBtn77;
        TBitBtn *BtULD_CmpUp;
        TBitBtn *BtULD_CmpDn;
        TPanel *pnULD_CmpUp;
        TPanel *pnULD_CmpDn;
    TGroupBox *GroupBox10;
    TLabel *Label88;
    TLabel *Label89;
        TLabel *lbCmdPos_YUld;
        TLabel *lbActPos_YUld;
    TLabel *Label92;
    TUpDown *UpDown9;
        TEdit *edMTPosJog8;
    TBitBtn *BitBtn106;
        TBitBtn *BtULD_PshFw;
        TBitBtn *BtULD_PshBw;
        TPanel *pnULD_PshFw;
        TPanel *pnULD_PshBw;
    TGroupBox *GroupBox5;
    TLabel *Label26;
    TLabel *Label27;
        TLabel *lbActPos_XIns;
    TLabel *Label30;
    TUpDown *UpDown4;
        TEdit *edMTPosJog7;
    TBitBtn *BitBtn29;
        TBitBtn *BtTrn_TransferUp;
        TBitBtn *BtTrn_TransferDn;
        TPanel *pnPRB_TrnUp;
        TPanel *pnPRB_TrnDn;
    TGroupBox *GroupBox6;
    TLabel *Label39;
    TLabel *Label42;
        TLabel *lbCmdPos_YFlp;
        TLabel *lbActPos_YFlp;
    TLabel *Label101;
    TUpDown *UpDown5;
        TEdit *edMTPosJog6;
    TBitBtn *BitBtn128;
    TGroupBox *GroupBox3;
    TLabel *Label12;
    TLabel *Label13;
        TLabel *lbCmdPos_XMrk;
        TLabel *lbActPos_XMrk;
    TLabel *Label16;
    TUpDown *UpDown1;
        TEdit *edMTPosJog4;
    TBitBtn *BitBtn15;
        TBitBtn *BtMrk_LiftUp;
        TBitBtn *BtMrk_LiftDn;
        TPanel *pnPSB_LiftUp;
        TPanel *pnPSB_LiftDn;
    TGroupBox *GroupBox4;
    TLabel *Label25;
    TLabel *Label40;
        TLabel *lbCmdPos_YMrk;
        TLabel *lbActPos_YMrk;
    TLabel *Label45;
    TUpDown *UpDown3;
        TEdit *edMTPosJog5;
    TBitBtn *BitBtn148;
        TBitBtn *BtMrk_MarkingUp;
        TBitBtn *BtMrk_MarkingDn;
        TPanel *pnPSB_CmpUp;
        TPanel *pnPSB_CmpDn;
    TGroupBox *GroupBox1;
    TLabel *Label1;
    TLabel *Label2;
        TLabel *lbCmdPos_XVsn;
        TLabel *lbActPos_XVsn;
    TLabel *Label5;
    TUpDown *UpDown;
        TEdit *edMTPosJog2;
        TBitBtn *BtMT_VisnXStop;
        TBitBtn *BtVisn2_LiftDn;
        TPanel *pnWR2_LiftUp;
        TPanel *pnWR2_LiftDn;
    TGroupBox *GroupBox2;
    TLabel *Label118;
    TLabel *Label119;
        TLabel *lbCmdPos_YVsn;
        TLabel *lbActPos_YVsn;
    TLabel *Label122;
    TUpDown *UpDown10;
        TEdit *edMTPosJog3;
        TBitBtn *BtMT_VisnYStop;
        TBitBtn *btSaveDevice;
        TPanel *pnLDR_ZPos;
        TPanel *pnLDR_YPos;
        TPanel *pnULD_ZPos;
        TPanel *pnULD_YPos;
        TPanel *pnPSB_XPos;
        TPanel *pnPSB_YPos;
        TPanel *pnWRK_XPos;
        TPanel *pnWRK_YPos;
        TPanel *pnWK1_XIns;
        TPanel *pnWK1_YFlp;
        TBitBtn *BtVisn2_LiftUp;
        TLabel *lbNLim_ZUld;
        TLabel *lbHome_ZUld;
        TLabel *lbAlar_ZUld;
        TLabel *lbPLim_ZUld;
        TLabel *lbServ_ZUld;
        TLabel *lbStop_ZUld;
        TLabel *lbHDon_ZUld;
        TLabel *lbNLim_YUld;
        TLabel *lbHome_YUld;
        TLabel *lbPLim_YUld;
        TLabel *lbAlar_YUld;
        TLabel *lbServ_YUld;
        TLabel *lbStop_YUld;
        TLabel *lbHDon_YUld;
        TLabel *lbNLim_XMrk;
        TLabel *lbHome_XMrk;
        TLabel *lbPLim_XMrk;
        TLabel *lbAlar_XMrk;
        TLabel *lbServ_XMrk;
        TLabel *lbStop_XMrk;
        TLabel *lbHDon_XMrk;
        TLabel *lbNLim_YMrk;
        TLabel *lbHome_YMrk;
        TLabel *lbPLim_YMrk;
        TLabel *lbAlar_YMrk;
        TLabel *lbServ_YMrk;
        TLabel *lbStop_YMrk;
        TLabel *lbNLim_XIns;
        TLabel *lbHome_XIns;
        TLabel *lbPLim_XIns;
        TLabel *lbAlar_XIns;
        TLabel *lbServ_XIns;
        TLabel *lbStop_XIns;
        TLabel *lbHDon_XIns;
        TLabel *lbNLim_YFlp;
        TLabel *lbHome_YFlp;
        TLabel *lbPLim_YFlp;
        TLabel *lbAlar_YFlp;
        TLabel *lbServ_YFlp;
        TLabel *lbStop_YFlp;
        TLabel *lbHDon_YFlp;
        TLabel *lbNLim_ZLdr;
        TLabel *lbHome_ZLdr;
        TLabel *lbPLim_ZLdr;
        TLabel *lbAlar_ZLdr;
        TLabel *lbServ_ZLdr;
        TLabel *lbStop_ZLdr;
        TLabel *lbHDon_ZLdr;
        TLabel *lbNLim_YLdr;
        TLabel *lbHome_YLdr;
        TLabel *lbPLim_YLdr;
        TLabel *lbAlar_YLdr;
        TLabel *lbServ_YLdr;
        TLabel *lbStop_YLdr;
        TLabel *lbHDon_YLdr;
        TLabel *lbNLim_XVsn;
        TLabel *lbHome_XVsn;
        TLabel *lbPLim_XVsn;
        TLabel *lbAlar_XVsn;
        TLabel *lbServ_XVsn;
        TLabel *lbStop_XVsn;
        TLabel *lbHDon_XVsn;
        TLabel *lbNLim_YVsn;
        TLabel *lbHome_YVsn;
        TLabel *lbPLim_YVsn;
        TLabel *lbAlar_YVsn;
        TLabel *lbServ_YVsn;
        TLabel *lbStop_YVsn;
        TLabel *lbHDon_YVsn;
        TLabel *lbCmdPos_XIns;
        TPanel *pnPRB_FeedingOn;
        TBitBtn *btWk1_FeedingOn;
        TBitBtn *btWk1_FeedingOff;
        TPanel *pnPRB_FeedingOff;
        TBitBtn *btMrkLeftUpPs;
        TBitBtn *btMrkLeftDnPs;
        TBitBtn *btMrkRightUpPs;
        TBitBtn *btMrkRightDnPs;
        TLabel *lbHDon_YMrk;
        TTimer *tmUpdateTimer;
        TBitBtn *btWR2_StprUp;
        TBitBtn *btWR2_StprDn;
        TPanel *pnWR2_StprUp;
        TPanel *pnWR2_StprDn;
        TBitBtn *btWR3_StprUp;
        TBitBtn *btWR3_StprDn;
        TPanel *pnWR3_StprUp;
        TPanel *pnWR3_StprDn;
        TBitBtn *BtVisn3_LiftUp;
        TBitBtn *BtVisn3_LiftDn;
        TPanel *pnWR3_LiftDn;
        TPanel *pnWR3_LiftUp;
        TBitBtn *btMrk_FeedingOn;
        TBitBtn *btMrk_FeedingOff;
        TPanel *pnPSB_FeedingOn;
        TPanel *pnPSB_FeedingOff;
        TBitBtn *btMrk_StprUp;
        TPanel *pnPSB_StprUp;
        TPanel *pnPSB_StprDn;
        TBitBtn *btMrk_StprDn;
        TBitBtn *btPRB_FlpCmpFw;
        TBitBtn *btPRB_FlpCmpBw;
        TPanel *pnPRB_FlpCmpUp;
        TPanel *pnPRB_FlpCmpDn;
        TBitBtn *btPSB_MrkYn;
        TBitBtn *btPSB_MrkXp;
        TBitBtn *btPSB_MrkYp;
        TBitBtn *btPSB_MrkXn;
        TBitBtn *btWR2_FeedingOn;
        TBitBtn *btWR2_FeedingOff;
        TPanel *pnWR2_FeedingOn;
        TPanel *pnWR2_FeedingOff;
        TBitBtn *BtWR1_StopperUp;
        TBitBtn *BtWR1_StopperDn;
        TPanel *pnWR1_StpUp;
        TPanel *pnWR1_StpDn;
        TBitBtn *btPRB_StprUp;
        TBitBtn *btPRB_StprDn;
        TPanel *pnPRB_StprDn;
        TPanel *pnPRB_StprUp;
        TImage *Image1;
        TImage *Image2;
        TBitBtn *btPSB_MrkChange;
        TPanel *pnPSB_MrkChange;
        TBitBtn *btBwdMove;
        TBitBtn *btFwdMove;
        TBitBtn *btBwdJog;
        TBitBtn *btFwdJog;
        TBitBtn *BtMt_VisnYBwUp;
        TBitBtn *BtMt_VisnYFwDn;
        TBitBtn *BtMt_VisnYBwUpJog;
        TBitBtn *BtMt_VisnYFwDnJog;
        TBitBtn *BitBtn1;
        TBitBtn *BitBtn2;
        TBitBtn *BitBtn3;
        TBitBtn *BitBtn4;
        TBitBtn *BitBtn5;
        TBitBtn *BitBtn6;
        TBitBtn *BitBtn7;
        TBitBtn *BitBtn8;
        TBitBtn *BitBtn9;
        TBitBtn *BitBtn10;
        TBitBtn *BitBtn11;
        TBitBtn *BitBtn12;
        TBitBtn *BitBtn13;
        TBitBtn *BitBtn14;
        TBitBtn *BitBtn16;
        TBitBtn *BitBtn17;
        TBitBtn *BitBtn18;
        TBitBtn *BitBtn19;
        TBitBtn *BitBtn20;
        TBitBtn *BitBtn21;
        TBitBtn *BitBtn22;
        TBitBtn *BitBtn23;
        TBitBtn *BitBtn24;
        TBitBtn *BitBtn25;
        TBitBtn *BitBtn26;
        TBitBtn *BitBtn27;
        TBitBtn *BitBtn28;
        TBitBtn *BitBtn30;
        TBitBtn *BitBtn31;
        TBitBtn *BitBtn32;
        TBitBtn *BitBtn33;
        TBitBtn *BitBtn34;
    void __fastcall UpDownChanging(TObject *Sender, bool &AllowChange);
        void __fastcall btSaveDeviceClick(TObject *Sender);
        void __fastcall FormShow(TObject *Sender);
        void __fastcall BtLDR_CmpUpClick(TObject *Sender);
        void __fastcall BtMT_VisnXStopClick(TObject *Sender);
        void __fastcall tmUpdateTimerTimer(TObject *Sender);
        void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
        void __fastcall FormDestroy(TObject *Sender);
        void __fastcall btWk1_FeedingOnClick(TObject *Sender);
        void __fastcall btWk1_FeedingOffClick(TObject *Sender);
        void __fastcall btMrkLeftUpPsClick(TObject *Sender);
        void __fastcall btMrkRightUpPsClick(TObject *Sender);
        void __fastcall btMrkLeftDnPsClick(TObject *Sender);
        void __fastcall btMrkRightDnPsClick(TObject *Sender);
        void __fastcall BtVisn2_LiftUpClick(TObject *Sender);
        void __fastcall btPSB_MrkYnClick(TObject *Sender);
        void __fastcall btPSB_MrkXpClick(TObject *Sender);
        void __fastcall btPSB_MrkXnClick(TObject *Sender);
        void __fastcall btPSB_MrkYpClick(TObject *Sender);
        void __fastcall BtLDR_CmpDnClick(TObject *Sender);
        bool __fastcall MotorCheck(EN_MOTR_ID _iMotor) ;
        void __fastcall btBwdMoveClick(TObject *Sender);
        void __fastcall btFwdMoveClick(TObject *Sender);
        void __fastcall btBwdJogMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btBwdJogMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btFwdJogMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
private:	// User declarations
//    void __fastcall UpdateDevOptn(bool bTable);
//    EN_MOTR_ID m_iMotor ;
//    bool bRet1;
public:		// User declarations
    __fastcall TFormMotorPos(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TFormMotorPos *FormMotorPos;
//---------------------------------------------------------------------------
#endif

