//---------------------------------------------------------------------------
#ifndef FormOperationH
#define FormOperationH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <Buttons.hpp>
#include <Graphics.hpp>
#include <ComCtrls.hpp>
//---------------------------------------------------------------------------
#include "SMDllDefine.h"
//#include "TEdit.h"
class TFrmOperation : public TForm
{
__published:	// IDE-managed Components
    TPanel *Panel1;
    TPanel *pnDataMap;
    TPanel *Panel4;
    TPanel *Panel5;
    TPanel *Panel6;
    TPanel *Panel7;
    TBitBtn *btStart;
    TBitBtn *btStop;
    TBitBtn *btReset;
    TBitBtn *btOperator;
    TPanel *plPassWord;
    TPanel *Panel19;
    TLabel *Label17;
    TBitBtn *btPasswordClose;
    TBitBtn *btEngr;
    TBitBtn *btOper;
    TBitBtn *btMast;
    TPanel *Panel8;
    TLabel *Label1;
    TLabel *Label3;
    TLabel *Label4;
    TLabel *Label5;
    TLabel *Label6;
    TPanel *Panel9;
        TPanel *pnDayRunTime;
        TPanel *pnDayIdleTime;
        TPanel *pnDayDayJamTime;
        TPanel *pnDayTotalTime;
        TPanel *pnDayChipUpeh;
    TPanel *Panel10;
    TLabel *Label2;
    TLabel *Label7;
    TLabel *Label8;
    TLabel *Label9;
    TLabel *Label10;
    TPanel *Panel11;
        TPanel *pnLotNo;
        TPanel *pnLotWorkChip;
        TPanel *pnLotChipUpeh;
        TPanel *pnLotStartTime;
        TPanel *pnLotRunTime;
    TPanel *Panel12;
    TPanel *Panel13;
        TPanel *pnNoTrmFail;
    TLabel *Label13;
    TPanel *pnNoTrimFail;
    TPanel *Panel32;
    TLabel *Label14;
    TPanel *pnIgnrDoor;
    TPanel *Panel34;
    TLabel *Label15;
        TPanel *pnVisn1Skip;
    TPanel *Panel36;
    TLabel *Label16;
        TPanel *pnCheckSFailCnt;
    TPanel *Panel14;
    TPanel *Panel15;
        TListBox *lbErr;
    TPanel *Panel16;
    TPanel *Panel18;
    TImage *Image2;
    TLabel *Label19;
    TImage *Image3;
    TLabel *Label20;
    TImage *Image4;
    TLabel *Label21;
    TImage *Image5;
    TLabel *Label22;
    TImage *Image6;
    TLabel *Label23;
    TImage *Image7;
    TLabel *Label24;
    TImage *Image8;
    TLabel *Label25;
        TTimer *tmUpdate;
        TBitBtn *btLotOpen;
        TBitBtn *btLotEnd;
        TLabel *Label31;
        TPanel *pnDayWorkChip;
        TLabel *Label32;
        TPanel *pnDayLotCount;
        TLabel *Label33;
        TPanel *pnLotFailChip;
        TLabel *Label34;
        TPanel *pnLotJobFile;
        TLabel *Label11;
        TPanel *pnDayFailChip;
        TLabel *lbSetNo;
        TLabel *lbInputCnt;
        TLabel *lbInputChar;
        TPanel *Panel20;
        TLabel *Label35;
        TPanel *pnVisn2Skip;
        TPanel *Panel3;
        TLabel *Label36;
        TPanel *pnCheckFailCnt;
        TEdit *edCheckFailCnt;
        TEdit *edCheckSFailCnt;
    TButton *Button6;
    TButton *Button7;
    TPanel *Panel2;
    TLabel *Label12;
    TPanel *pnTrimCheck;
        TPageControl *pcMan;
        TTabSheet *TabSheet2;
        TBitBtn *btMan2_1;
        TBitBtn *btMan2_2;
        TBitBtn *btMan2_7;
        TBitBtn *btMan2_3;
        TBitBtn *btMan2_4;
        TBitBtn *btMan2_5;
        TBitBtn *btMan2_6;
        TBitBtn *btMan2_8;
        TBitBtn *btMan2_9;
        TBitBtn *btMan2_10;
        TBitBtn *btMan2_11;
        TBitBtn *btMan2_12;
        TBitBtn *btMan2_13;
        TBitBtn *btMan2_14;
        TTabSheet *TabSheet3;
        TBitBtn *btMan3_1;
        TBitBtn *btMan3_2;
        TBitBtn *btMan3_7;
        TBitBtn *btMan3_3;
        TBitBtn *btMan3_4;
        TBitBtn *btMan3_5;
        TBitBtn *btMan3_6;
        TBitBtn *btMan3_8;
        TBitBtn *btMan3_9;
        TBitBtn *btMan3_10;
        TBitBtn *btMan3_11;
        TBitBtn *btMan3_12;
        TBitBtn *btMan3_13;
        TBitBtn *btMan3_14;
        TTabSheet *TabSheet9;
        TBitBtn *btMan4_1;
        TBitBtn *btMan4_2;
        TBitBtn *btMan4_7;
        TBitBtn *btMan4_3;
        TBitBtn *btMan4_4;
        TBitBtn *btMan4_5;
        TBitBtn *btMan4_6;
        TBitBtn *btMan4_8;
        TBitBtn *btMan4_9;
        TBitBtn *btMan4_10;
        TBitBtn *btMan4_11;
        TBitBtn *btMan4_12;
        TBitBtn *btMan4_13;
        TBitBtn *btMan4_14;
        TTabSheet *TabSheet1;
        TBitBtn *btMan7_1;
        TBitBtn *btMan7_2;
        TBitBtn *btMan7_7;
        TBitBtn *btMan7_3;
        TBitBtn *btMan7_4;
        TBitBtn *btMan7_5;
        TBitBtn *btMan7_6;
        TBitBtn *btMan7_8;
        TBitBtn *btMan7_9;
        TBitBtn *btMan7_10;
        TBitBtn *btMan7_11;
        TBitBtn *btMan7_12;
        TBitBtn *btMan7_13;
        TBitBtn *btMan7_14;
        TTabSheet *TabSheet8;
        TBitBtn *btMan5_1;
        TBitBtn *btMan5_2;
        TBitBtn *btMan5_7;
        TBitBtn *btMan5_3;
        TBitBtn *btMan5_4;
        TBitBtn *btMan5_5;
        TBitBtn *btMan5_6;
        TBitBtn *btMan5_8;
        TBitBtn *btMan5_9;
        TBitBtn *btMan5_10;
        TBitBtn *btMan5_11;
        TBitBtn *btMan5_12;
        TBitBtn *btMan5_13;
        TBitBtn *btMan5_14;
        TTabSheet *tsETC;
        TBitBtn *btMan6_1;
        TBitBtn *btMan6_2;
        TBitBtn *btMan6_7;
        TBitBtn *btMan6_3;
        TBitBtn *btMan6_4;
        TBitBtn *btMan6_5;
        TBitBtn *btMan6_6;
        TBitBtn *btMan6_8;
        TBitBtn *btMan6_9;
        TBitBtn *btMan6_10;
        TBitBtn *btMan6_11;
        TBitBtn *btMan6_12;
        TBitBtn *btMan6_13;
        TBitBtn *btMan6_14;
        TTabSheet *tsLoader;
        TBitBtn *btMan1_1;
        TBitBtn *btMan1_2;
        TBitBtn *btMan1_7;
        TBitBtn *btMan1_3;
        TBitBtn *btMan1_4;
        TBitBtn *btMan1_5;
        TBitBtn *btMan1_6;
        TBitBtn *btMan1_8;
        TBitBtn *btMan1_9;
        TBitBtn *btMan1_10;
        TBitBtn *btMan1_11;
        TBitBtn *btMan1_12;
        TBitBtn *btMan1_13;
        TBitBtn *btMan1_14;
        TGroupBox *Label28;
        TPanel *pnUnLoader;
        TGroupBox *Label30;
        TLabel *Label37;
        TLabel *Label38;
        TLabel *Label39;
        TPanel *pnPreBuff;
        TButton *btPrbClear;
        TEdit *edPrbLotNo;
        TButton *btPrbLotInput;
        TEdit *edPrbSlotNo;
        TEdit *edPrbMgzNo;
        TLabel *lbPRBLotNo;
        TGroupBox *Label29;
        TLabel *Label40;
        TLabel *Label41;
        TLabel *Label42;
        TPanel *pnPostBuff;
        TButton *btPsbClear;
        TButton *btNoTrimPSB;
        TEdit *edPsbLotNo;
        TButton *btPsbLotInput;
        TEdit *edPsbSlotNo;
        TEdit *edPsbMgzNo;
        TGroupBox *GroupBox2;
        TGroupBox *GroupBox3;
        TLabel *Label43;
        TLabel *Label44;
        TLabel *Label45;
        TPageControl *PageControl2;
        TTabSheet *TabSheet4;
        TPanel *pnInsp1;
        TTabSheet *tsVs1;
        TPanel *pnVisn1;
        TButton *btVisn1Reset;
        TButton *btVs1Clear;
        TButton *btNoTrimWK1;
        TEdit *edVs1LotNo;
        TButton *btVs1LotInput;
        TEdit *edVs1SlotNo;
        TEdit *edVs1MgzNo;
        TLabel *Label46;
        TLabel *Label47;
        TLabel *Label48;
        TPageControl *PageControl3;
        TTabSheet *TabSheet6;
        TPanel *pnInsp2;
        TTabSheet *tsVs2;
        TPanel *pnVisn2;
        TButton *btVs2Clear;
        TButton *Button5;
        TButton *btNoTrimWK2;
        TEdit *edVs2LotNo;
        TButton *btVs2LotInput;
        TEdit *edVs2SlotNo;
        TEdit *edVs2MgzNo;
        TGroupBox *lbLoader;
        TPanel *pnLoader;
    void __fastcall FormShow(TObject *Sender);
    void __fastcall btOperatorClick(TObject *Sender);
    void __fastcall btPasswordCloseClick(TObject *Sender);
    void __fastcall btOperClick(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall tmUpdateTimer(TObject *Sender);
    void __fastcall pnDataMapMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall imBuff1MouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall imBuff1MouseUp(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall imBuff1MouseMove(TObject *Sender, TShiftState Shift,
          int X, int Y);
        void __fastcall pcManChange(TObject *Sender);
        void __fastcall btLotOpenClick(TObject *Sender);
        void __fastcall btStartClick(TObject *Sender);
        void __fastcall btStopClick(TObject *Sender);
        void __fastcall btResetClick(TObject *Sender);
        void __fastcall btLotEndClick(TObject *Sender);
    void __fastcall pnDryRunDblClick(TObject *Sender);
        void __fastcall btManClick(TObject *Sender);
        void __fastcall btVisn1ResetClick(TObject *Sender);
        void __fastcall btPrbClearClick(TObject *Sender);
        void __fastcall btPsbClearClick(TObject *Sender);
        void __fastcall btVs1ClearClick(TObject *Sender);
        void __fastcall btVs2ClearClick(TObject *Sender);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall Button5Click(TObject *Sender);
        void __fastcall Button6Click(TObject *Sender);
    void __fastcall Button7Click(TObject *Sender);
        void __fastcall btNoTrimWK2Click(TObject *Sender);
        void __fastcall btNoTrimWK1Click(TObject *Sender);
        void __fastcall btNoTrimPSBClick(TObject *Sender);
        void __fastcall edCheckSFailCntChange(TObject *Sender);
        void __fastcall edCheckFailCntChange(TObject *Sender);
    void __fastcall btPrbLotInputClick(TObject *Sender);

private:	// User declarations
    bool __fastcall LanguageSel(EN_LAN_SEL lvType);
public:		// User declarations
    __fastcall TFrmOperation(TComponent* Owner);
    bool __fastcall CheckStripDisappear();
};
//---------------------------------------------------------------------------
extern PACKAGE TFrmOperation *FrmOperation;
//---------------------------------------------------------------------------
#endif

