//---------------------------------------------------------------------------
#ifndef FormOperationH
#define FormOperationH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <Buttons.hpp>
//---------------------------------------------------------------------------
//#include "FormPassword.h"
#include <Graphics.hpp>
#include <ComCtrls.hpp>
#include <Grids.hpp>
#include <jpeg.hpp>
class TFrmOperation : public TForm
{
__published:	// IDE-managed Components
    TPanel *Panel1;
    TPanel *pnDataMap;
    TPanel *Panel3;
    TPanel *Panel4;
    TPanel *Panel5;
    TPanel *Panel6;
    TPanel *Panel7;
    TBitBtn *btStart;
    TBitBtn *btStop;
    TBitBtn *btReset;
    TBitBtn *btOperator;
    TPanel *plPassWord;
    TPanel *Panel19;
    TLabel *Label17;
    TBitBtn *btPasswordClose;
    TBitBtn *btEngr;
    TBitBtn *btOper;
    TBitBtn *btMast;
    TPanel *Panel8;
    TPanel *Panel9;
    TPanel *Panel10;
    TPanel *Panel11;
    TPanel *Panel12;
    TPanel *Panel13;
    TPanel *Panel14;
    TPanel *Panel15;
    TListBox *lbErr;
    TPanel *Panel16;
    TPanel *Panel18;
    TImage *Image1;
    TLabel *Label18;
    TImage *Image2;
    TLabel *Label19;
    TImage *Image3;
    TLabel *Label20;
    TImage *Image4;
    TLabel *Label21;
    TImage *Image5;
    TLabel *Label22;
    TImage *Image6;
    TLabel *Label23;
    TImage *Image7;
    TLabel *Label24;
    TImage *Image8;
    TLabel *Label25;
    TTimer *tmUpdate;
    TBitBtn *btLotOpen;
    TBitBtn *btLotEnd;
    TLabel *Label1;
    TLabel *Label3;
    TLabel *Label4;
    TLabel *Label5;
    TLabel *Label6;
    TLabel *Label31;
    TLabel *Label32;
    TPanel *pnDayRunTime;
    TPanel *pnDayIdleTime;
    TPanel *pnDayJamTime;
    TPanel *pnDayTotalTime;
    TPanel *pnDayChipUpeh;
    TPanel *pnDayWorkChip;
    TPanel *pnDayLotCount;
        TPageControl *pcManual;
    TTabSheet *TabSheet1;
    TTabSheet *TabSheet2;
    TTabSheet *TabSheet3;
    TTabSheet *TabSheet4;
    TLabel *Label16;
    TPanel *pnDayFailChip;
    TLabel *Label2;
    TLabel *Label7;
    TLabel *Label8;
    TLabel *Label9;
    TLabel *Label10;
    TLabel *Label33;
    TLabel *Label34;
    TPanel *pnLotNo;
    TPanel *pnLotWorkChip;
    TPanel *pnLotChipUpeh;
    TPanel *pnLotStartTime;
    TPanel *pnLotRunTime;
    TPanel *pnLotFailChip;
    TPanel *pnLotJobFile;
    TTabSheet *TabSheet11;
        TBitBtn *btMan1_1;
        TBitBtn *btMan1_2;
        TBitBtn *btMan1_7;
        TBitBtn *btMan1_3;
        TBitBtn *btMan1_4;
        TBitBtn *btMan1_5;
        TBitBtn *btMan1_6;
        TBitBtn *btMan1_8;
        TBitBtn *btMan1_9;
        TBitBtn *btMan1_10;
        TBitBtn *btMan1_11;
        TBitBtn *btMan1_12;
        TBitBtn *btMan1_13;
        TBitBtn *btMan1_14;
        TBitBtn *btMan2_1;
        TBitBtn *btMan2_2;
        TBitBtn *btMan2_7;
        TBitBtn *btMan2_3;
        TBitBtn *btMan2_4;
        TBitBtn *btMan2_5;
        TBitBtn *btMan2_6;
        TBitBtn *btMan2_8;
        TBitBtn *btMan2_9;
        TBitBtn *btMan2_10;
        TBitBtn *btMan2_11;
        TBitBtn *btMan2_12;
        TBitBtn *btMan2_13;
        TBitBtn *btMan2_14;
        TBitBtn *btMan3_1;
        TBitBtn *btMan3_2;
        TBitBtn *btMan3_7;
        TBitBtn *btMan3_3;
        TBitBtn *btMan3_4;
        TBitBtn *btMan3_5;
        TBitBtn *btMan3_6;
        TBitBtn *btMan3_8;
        TBitBtn *btMan3_9;
        TBitBtn *btMan3_10;
        TBitBtn *btMan3_11;
        TBitBtn *btMan3_12;
        TBitBtn *btMan3_13;
        TBitBtn *btMan3_14;
        TBitBtn *btMan4_1;
        TBitBtn *btMan4_2;
        TBitBtn *btMan4_7;
        TBitBtn *btMan4_3;
        TBitBtn *btMan4_4;
        TBitBtn *btMan4_5;
        TBitBtn *btMan4_6;
        TBitBtn *btMan4_8;
        TBitBtn *btMan4_9;
        TBitBtn *btMan4_10;
        TBitBtn *btMan4_11;
        TBitBtn *btMan4_12;
        TBitBtn *btMan4_13;
        TBitBtn *btMan4_14;
        TBitBtn *btMan5_1;
        TBitBtn *btMan5_2;
        TBitBtn *btMan5_7;
        TBitBtn *btMan5_3;
        TBitBtn *btMan5_4;
        TBitBtn *btMan5_5;
        TBitBtn *btMan5_6;
        TBitBtn *btMan5_8;
        TBitBtn *btMan5_9;
        TBitBtn *btMan5_10;
        TBitBtn *btMan5_11;
        TBitBtn *btMan5_12;
        TBitBtn *btMan5_13;
        TBitBtn *btMan5_14;
        TTabSheet *TabSheet12;
    TBitBtn *btMan6_1;
    TBitBtn *btMan6_8;
    TBitBtn *btMan6_2;
    TBitBtn *btMan6_9;
    TBitBtn *btMan6_3;
    TBitBtn *btMan6_10;
    TBitBtn *btMan6_4;
    TBitBtn *btMan6_11;
    TBitBtn *btMan6_5;
    TBitBtn *btMan6_12;
    TBitBtn *btMan6_6;
    TBitBtn *btMan6_13;
    TBitBtn *btMan6_7;
    TBitBtn *btMan6_14;
    TPanel *Panel32;
    TLabel *Label14;
    TPanel *pnDoorSkip;
    TPanel *Panel2;
    TLabel *Label13;
    TPanel *pnVisn1NotUse;
    TPanel *Panel34;
    TLabel *Label15;
    TPanel *pnVisn2NotUse;
    TPanel *Panel22;
    TPanel *pnCheckFailCnt;
    TPanel *Panel25;
    TPanel *Panel23;
    TLabel *Label28;
    TPanel *pnAfterMrkRemove;
    TPanel *Panel21;
    TLabel *Label11;
    TPanel *pnVisn3NotUse;
    TPanel *Panel17;
    TGroupBox *GroupBox1;
    TPanel *pnLoader;
    TGroupBox *GroupBox2;
    TGroupBox *GroupBox4;
    TLabel *Label40;
    TPageControl *pcWorkZone1;
    TTabSheet *TabSheet9;
    TPanel *pn1B1;
    TTabSheet *TabSheet10;
    TPanel *pnInsp1;
    TButton *btWK1Clear;
    TButton *btWk1Input;
    TGroupBox *GroupBox5;
    TButton *btWk2Input;
    TLabel *lbCnt;
    TLabel *lbCntRe;
    TGroupBox *GroupBox3;
    TPageControl *pcPostBuff;
    TTabSheet *TabSheet5;
    TPanel *pnPSB;
    TTabSheet *TabSheet6;
    TPanel *pnVisn4;
    TButton *btWk4Input;
    TTabSheet *TabSheet15;
    TPageControl *pcWorkZone2;
    TTabSheet *TabSheet7;
    TPanel *pn2B2;
    TTabSheet *TabSheet8;
    TPanel *pnInsp2;
    TTabSheet *TabSheet16;
    TPanel *pnVisn2;
    TGroupBox *GroupBox6;
    TButton *btWk3Input;
    TPageControl *pcWorkZone3;
    TTabSheet *TabSheet13;
    TPanel *pn3B3;
    TTabSheet *TabSheet14;
    TPanel *pnInsp3;
    TTabSheet *TabSheet17;
    TPanel *pnVisn3;
    TButton *btWK2Clear;
    TButton *btPSBClear;
    TPanel *pnVisn1;
    TGroupBox *gbChipColor;
    TLabel *lbR1;
    TLabel *lbR2;
    TLabel *lbR3;
    TLabel *lbR4;
    TLabel *lbR5;
    TLabel *lbR6;
    TLabel *lbR7;
    TLabel *lbR8;
    TLabel *lbR9;
    TLabel *lbR10;
    TLabel *lbR11;
    TLabel *lbR12;
    TLabel *lbR13;
    TLabel *lbR14;
    TPanel *Panel20;
    TPanel *pnColor1;
    TPanel *pnColor2;
    TPanel *pnColor3;
    TPanel *pnColor4;
    TPanel *pnColor5;
    TPanel *pnColor6;
    TPanel *pnColor7;
    TPanel *pnColor8;
    TPanel *pnColor9;
    TPanel *pnColor10;
    TPanel *pnColor11;
    TPanel *pnColor12;
    TPanel *pnColor13;
    TPanel *pnColor14;
    TButton *btWK3Clear;
    TPanel *pnMarkingSkip;
    TLabel *Label12;
    TPanel *pnVisnMrkNotUse;
    TLabel *Label36;
    TLabel *Label27;
    TEdit *edLimAllFailCnt;
    TGroupBox *GroupBox7;
    TPanel *pnPRB;
    TGroupBox *GroupBox8;
    TPanel *pnWorkTray;
    TGroupBox *GroupBox9;
    TPanel *pnUnLoader;
    TGroupBox *GroupBox10;
    TButton *btULDClear;
    TPanel *pnULD;
    TButton *btPRBClear;
    TLabel *Label39;
    TPanel *pnLotGoodChip;
    TPanel *pnLotMGZCnt2;
    TLabel *Label46;
    TEdit *edMeasure;
    TBitBtn *btnOK;
    TEdit *edWk1LotNo;
    TEdit *edWk1Id;
    TLabel *Label41;
    TEdit *edWk2Id;
    TLabel *Label42;
    TEdit *edWk2LotNo;
    TLabel *Label43;
    TEdit *edWk4Id;
    TLabel *Label26;
    TEdit *edWk4LotNo;
    TLabel *Label29;
    TEdit *edWk3Id;
    TLabel *Label30;
    TEdit *edWk3LotNo;
    TLabel *Label35;
    TTimer *tmUpdate1;
    TButton *btVS1Reset;
    TButton *btVS2Reset;
    TButton *btVS3Reset;
    TButton *btPSBReset;
    TStaticText *lbVs1FailCnt;
    TStaticText *lbVs2FailCnt;
    TStaticText *lbVs3FailCnt;
    TStaticText *lbMrkFailCnt;
    TPanel *Panel24;
    TLabel *lbFailName1;
    TLabel *lbFailName2;
    TLabel *lbFailName3;
    TLabel *lbFailName4;
    TLabel *lbFailName5;
    TLabel *lbFailName6;
    TLabel *lbFailName7;
    TLabel *lbFailName8;
    TLabel *lbFailName9;
    TLabel *lbFailName10;
    TLabel *lbFailName11;
    TLabel *lbFailName12;
    TLabel *lbFailName13;
    TLabel *lbFailName14;
    TLabel *lbFailName15;
    TLabel *Label44;
    TLabel *Label45;
    TLabel *Label37;
    TLabel *Label47;
    TLabel *Label48;
    TLabel *Label50;
    TLabel *Label51;
    TLabel *Label52;
    TLabel *Label53;
    TLabel *Label54;
    TLabel *Label55;
    TLabel *Label56;
    TLabel *Label57;
    TLabel *Label58;
    TLabel *Label59;
    TLabel *Label38;
    TLabel *Label49;
    TEdit *edRslt1;
    TEdit *edRslt2;
    TEdit *edRslt3;
    TEdit *edRslt4;
    TEdit *edRslt5;
    TEdit *edRslt6;
    TEdit *edRslt7;
    TEdit *edRslt8;
    TEdit *edRslt9;
    TEdit *edRslt10;
    TEdit *edRslt11;
    TEdit *edRslt12;
    TEdit *edRslt13;
    TEdit *edRslt14;
    TEdit *edFail;
    TEdit *edTotal;
    TEdit *edLastTrayCnt;
    TPanel *Panel26;
    TImage *Image9;
    TLabel *Label60;
        TPanel *pnLotCnt;
    void __fastcall FormShow(TObject *Sender);
    void __fastcall btOperatorClick(TObject *Sender);
    void __fastcall btPasswordCloseClick(TObject *Sender);
    void __fastcall btOperClick(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
        void __fastcall btLotOpenClick(TObject *Sender);
        void __fastcall btStartClick(TObject *Sender);
        void __fastcall btStopClick(TObject *Sender);
        void __fastcall btResetClick(TObject *Sender);
        void __fastcall btLotEndClick(TObject *Sender);
    void __fastcall pnMarkingSkipDblClick(TObject *Sender);
    void __fastcall btMan1_1Click(TObject *Sender);
        void __fastcall btWK2ClearClick(TObject *Sender);
        void __fastcall btWK1ClearClick(TObject *Sender);
    void __fastcall pnDayRunTimeDblClick(TObject *Sender);
    void __fastcall GroupBox1Click(TObject *Sender);
    void __fastcall btWK3ClearClick(TObject *Sender);
    void __fastcall btPSBClearClick(TObject *Sender);
    void __fastcall gbChipColorClick(TObject *Sender);
    void __fastcall Label27Click(TObject *Sender);
    void __fastcall btPRBClearClick(TObject *Sender);
    void __fastcall btULDClearClick(TObject *Sender);
    void __fastcall pnLotNoClick(TObject *Sender);
    void __fastcall btnOKClick(TObject *Sender);
    void __fastcall btWk1InputClick(TObject *Sender);
    void __fastcall tmUpdate1Timer(TObject *Sender);
    void __fastcall FormDestroy(TObject *Sender);
    void __fastcall btVS1ResetClick(TObject *Sender);

private:	// User declarations

public:		// User declarations
    __fastcall TFrmOperation(TComponent* Owner);
    bool __fastcall CheckStripDisappear();
    bool __fastcall CheckStripUnknwon  ();
    void __fastcall LbResultChange();
    bool GetLastStrip();
    bool bTemp;
};
//---------------------------------------------------------------------------
extern PACKAGE TFrmOperation *FrmOperation;
//---------------------------------------------------------------------------
#endif
