//---------------------------------------------------------------------------

#ifndef FormDeviceSetH
#define FormDeviceSetH
//---------------------------------------------------------------------------
#include "UserFile.h"
#include "TEdit.h"
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Buttons.hpp>
#include <jpeg.hpp>
#include <Grids.hpp>
//---------------------------------------------------------------------------
//#include "Timer.h"
#include "FrameCyl.h"
#include "FrameMotr.h"
//#include <ImgList.hpp>

class TFrmDeviceSet : public TForm
{
__published:	// IDE-managed Components
    TTimer *tmUpdateTimer;
        TPageControl *pcDeviceSet;
        TTabSheet *tsDeviceInfo;
        TTabSheet *TabSheet3;
        TPanel *Panel6;
    TPageControl *pcLoader1;
    TTabSheet *tabLD1_MT1;
        TTabSheet *TabSheet4;
        TTabSheet *TabSheet1;
        TTabSheet *TabSheet7;
        TBitBtn *btSaveDevice;
        TTabSheet *TabSheet12;
    TTabSheet *TabSheet5;
    TPanel *Panel26;
    TRadioGroup *rgULDJogUnit2;
    TEdit *edULDJogUnit2;
    TPageControl *pcUnLoader2;
    TTabSheet *tabULD2_1;
    TPanel *Panel31;
    TRadioGroup *rgPSBJogUnit;
    TEdit *edPSBJogUnit;
    TPageControl *PageControl5;
    TTabSheet *TabSheet11;
    TPageControl *PageControl7;
    TTabSheet *TabSheet13;
    TGroupBox *GroupBox10;
    TImage *Image2;
    TLabel *Label10;
    TLabel *Label11;
    TLabel *Label12;
    TLabel *Label13;
    TStaticText *lbRowPitch;
    TEdit *edRowPitch;
    TStaticText *lbColPitch;
    TEdit *edColPitch;
    TStaticText *lbRowGroupCount;
    TEdit *edRowGroupCount;
    TStaticText *lbColCount;
    TEdit *edColCount;
    TStaticText *lbRowGroupGap;
    TEdit *edRowGroupGap;
    TStaticText *lbColGroupGap;
    TEdit *edColGroupGap;
    TStaticText *lbRowCount;
    TEdit *edRowCount;
    TStaticText *lbSrColCntrPitch;
    TEdit *edColGroupCount;
    TTabSheet *TabSheet14;
    TGroupBox *GroupBox19;
    TStaticText *StaticText61;
    TEdit *edLDRColCnt;
    TStaticText *StaticText62;
    TEdit *edLDRColPitch;
    TStaticText *StaticText63;
    TEdit *edLDRRowCnt;
    TStaticText *StaticText64;
    TEdit *edLDRRowPitch;
    TGroupBox *GroupBox11;
    TImage *Image3;
    TStaticText *StaticText8;
    TEdit *edULDColCnt;
    TStaticText *StaticText10;
    TEdit *edULDColPitch;
    TStaticText *StaticText59;
    TEdit *edULDPkgCnt;
    TImage *Image1;
    TLabel *Label75;
    TLabel *Label76;
    TLabel *Label77;
    TLabel *Label78;
    TLabel *Label79;
    TStaticText *StaticText11;
    TEdit *edULDRowCnt;
    TStaticText *StaticText12;
    TEdit *edULDRowPitch;
    TPanel *Panel22;
    TRadioGroup *rgULDJogUnit1;
    TEdit *edULDJogUnit1;
    TPageControl *pcUnLoader1;
    TTabSheet *tabULD1_1;
    TTabSheet *tabULD1_2;
    TTabSheet *tabULD2_2;
    TPanel *Panel1;
    TPageControl *pcWork1;
    TTabSheet *tabWK1_MT1;
    TTabSheet *tabWK1_MT2;
    TRadioGroup *rgWK1JogUnit;
    TEdit *edWK1JogUnit;
    TPanel *Panel2;
    TPageControl *pcWorkVsn;
    TTabSheet *tabWRK_MT1;
    TTabSheet *tabWRK_MT2;
    TRadioGroup *rgWRKJogUnit;
    TEdit *edWRKJogUnit;
    TPanel *Panel8;
    TPanel *Panel9;
    TImage *Image11;
    TLabel *Label5;
    TPanel *pnLDR_XPsh;
    TPanel *Panel10;
    TPanel *Panel11;
    TImage *Image5;
    TLabel *Label6;
    TPanel *pnLDR_YFed;
    TGroupBox *GroupBox1;
    TPanel *pnLDR_XPshMT;
    TGroupBox *GroupBox21;
    TPanel *pnLDR_YFedMT;
    TPanel *Panel16;
    TPanel *Panel17;
    TImage *Image12;
    TLabel *Label3;
    TPanel *pnWK1_YFlp;
    TPanel *Panel23;
    TPanel *Panel25;
    TImage *Image13;
    TLabel *Label4;
    TPanel *pnWK1_XIns;
    TPanel *Panel52;
    TPanel *Panel53;
    TImage *Image15;
    TLabel *Label15;
    TGroupBox *GroupBox61;
    TPanel *pnPRB_Stpr;
    TGroupBox *GroupBox62;
    TPanel *pnWK1_Stpr;
    TGroupBox *GroupBox63;
    TPanel *pnWK1_Algn;
    TGroupBox *GroupBox64;
    TPanel *pnWK1_Flp;
    TGroupBox *GroupBox65;
    TPanel *pnWK1_Ins;
    TGroupBox *GroupBox2;
    TPanel *pnWK1_YFlpMT;
    TGroupBox *GroupBox12;
    TPanel *pnWK1_XInsMT;
    TGroupBox *GroupBox37;
    TPanel *pnWRK_XVsnMT;
    TGroupBox *GroupBox46;
    TPanel *pnWRK_YVsnMT;
    TRadioGroup *rgLDRJogUnit;
    TEdit *edLDRJogUnit;
    TPanel *Panel3;
    TPanel *Panel4;
    TImage *Image16;
    TLabel *Label1;
    TPanel *pnWRK_XVsn;
    TPanel *Panel19;
    TPanel *Panel20;
    TImage *Image17;
    TLabel *Label2;
    TPanel *pnWRK_YVsn;
    TPanel *Panel44;
    TPanel *Panel54;
    TImage *Image18;
    TLabel *Label16;
    TGroupBox *GroupBox5;
    TPanel *pnWK2_Stpr;
    TGroupBox *GroupBox9;
    TPanel *pnWK2_Algn;
    TGroupBox *GroupBox66;
    TPanel *pnWK3_Stpr;
    TGroupBox *GroupBox67;
    TPanel *pnWK3_Algn;
    TGroupBox *GroupBox7;
    TPanel *pnWK1_YFlpMT2;
    TGroupBox *GroupBox8;
    TPanel *pnWK1_XInsMT2;
    TGroupBox *GroupBox13;
    TPanel *pnWRK_XVsnMT2;
    TGroupBox *GroupBox18;
    TPanel *pnWRK_YVsnMT2;
    TPanel *Panel18;
    TPanel *Panel21;
    TImage *Image19;
    TLabel *Label17;
    TPanel *pnPSB_XMrk;
    TPanel *Panel32;
    TPanel *Panel33;
    TImage *Image20;
    TLabel *Label18;
    TPanel *pnPSB_YMrk;
    TPanel *Panel55;
    TPanel *Panel56;
    TImage *Image21;
    TLabel *Label19;
    TGroupBox *GroupBox24;
    TPanel *pnPSB_Stpr;
    TGroupBox *GroupBox26;
    TPanel *pnPSB_Algn;
    TGroupBox *GroupBox47;
    TPanel *pnPSB_Mrk;
    TGroupBox *GroupBox48;
    TPanel *pnPSB_RjctFB;
    TGroupBox *GroupBox68;
    TPanel *pnPSB_RjctUD;
    TGroupBox *GroupBox20;
    TPanel *pnPSB_XMrkMT;
    TGroupBox *GroupBox30;
    TPanel *pnPSB_YMrkMT;
    TPanel *Panel5;
    TPanel *Panel7;
    TImage *Image22;
    TLabel *Label20;
    TPanel *pnULD_ZPck;
    TPanel *Panel36;
    TPanel *Panel57;
    TImage *Image25;
    TLabel *Label22;
    TPanel *pnULD_YPck;
    TPanel *Panel59;
    TPanel *Panel60;
    TImage *Image26;
    TLabel *Label23;
    TGroupBox *GroupBox29;
    TPanel *pnULD_Cmp;
    TGroupBox *GroupBox32;
    TPanel *pnULD_Pck;
    TGroupBox *GroupBox34;
    TPanel *pnULD_Move;
    TGroupBox *GroupBox70;
    TPanel *pnULD_Open;
    TGroupBox *GroupBox36;
    TPanel *pnULD_ZPckMT;
    TGroupBox *GroupBox41;
    TPanel *pnULD_YPckMT;
    TGroupBox *GroupBox42;
    TPanel *pnULD_XStpMT;
    TGroupBox *GroupBox6;
    TPanel *pnULD_ZTrOMT;
    TGroupBox *GroupBox17;
    TPanel *pnULD_ZTrIMT;
    TGroupBox *GroupBox33;
        TPanel *pnULD_ZPprMT;
    TGroupBox *GroupBox4;
    TPanel *pnULD_YPckMT2;
    TGroupBox *GroupBox27;
    TPanel *pnULD_XStpMT2;
    TGroupBox *GroupBox35;
    TPanel *pnULD_ZPckMT2;
    TGroupBox *GroupBox50;
    TPanel *pnULD_ZTrOMT2;
    TGroupBox *GroupBox51;
    TPanel *pnULD_ZTrIMT2;
    TGroupBox *GroupBox52;
        TPanel *pnULD_ZPprMT2;
    TGroupBox *GroupBox53;
    TPanel *pnULD_Hold;
    TPanel *Panel58;
    TPanel *Panel61;
    TImage *Image28;
    TLabel *Label25;
        TPanel *pnULD_ZPpr;
    TPanel *Panel63;
    TPanel *Panel64;
    TImage *Image29;
    TLabel *Label26;
    TPanel *pnULD_ZTrI;
    TPanel *Panel66;
    TPanel *Panel67;
    TImage *Image30;
    TLabel *Label27;
    TPanel *pnULD_ZTrO;
    TPanel *Panel13;
    TPanel *Panel35;
    TImage *Image27;
    TLabel *Label24;
    TGroupBox *GroupBox40;
    TPanel *pnULD_Cmp2;
    TGroupBox *GroupBox54;
    TPanel *pnULD_Pck2;
    TGroupBox *GroupBox55;
    TPanel *pnULD_Move2;
    TGroupBox *GroupBox71;
    TPanel *pnULD_Cnvs2;
    TGroupBox *GroupBox72;
    TPanel *pnULD_Open2;
    TGroupBox *GroupBox73;
    TPanel *pnULD_Hold2;
    TPanel *Panel28;
    TPanel *Panel34;
    TImage *Image23;
    TLabel *Label21;
    TPanel *pnULD_XStp;
    TGroupBox *GroupBox3;
    TBitBtn *btPRB_Feeding;
    TGroupBox *GroupBox25;
    TBitBtn *btPRB_Feeding2;
    TGroupBox *GroupBox28;
    TBitBtn *btPSB_Feeding;
    TGroupBox *GroupBox49;
    TBitBtn *btULD_Feeding;
    TGroupBox *GroupBox74;
    TBitBtn *btULD_Feeding2;
    TGroupBox *GroupBox75;
    TBitBtn *btWRK_Feeding;
    TLabel *Label28;
    TLabel *Label29;
    TPanel *Panel24;
    TPanel *Panel12;
    TImage *Image24;
    TLabel *Label7;
    TGroupBox *GroupBox38;
    TPanel *pnLDR_Pusher;
    TGroupBox *GroupBox56;
    TPanel *pnLDR_Rotator;
    TGroupBox *GroupBox57;
    TPanel *pnLDR_Clamp;
    TGroupBox *GroupBox58;
    TPanel *pnLDR_InMgz;
    TGroupBox *GroupBox59;
    TPanel *pnLDR_OutMgz;
    TImage *Image7;
        TPanel *Panel45;
        TPanel *Panel51;
        TImage *Image9;
        TLabel *Label14;
        TPanel *pnLDR_XPck;
        TGroupBox *GroupBox31;
        TPanel *pnLDR_XPckMT;
        TGroupBox *GroupBox43;
        TPanel *pnLDR_ZPckMT;
        TPanel *Panel42;
        TPanel *Panel43;
        TImage *Image8;
        TLabel *Label9;
        TPanel *pnLDR_ZPck;
    TGroupBox *GroupBox14;
    TLabel *Label8;
    TLabel *Label31;
    TEdit *edInsColCnt;
    TStaticText *StaticText30;
    TEdit *edInsRowCnt;
    TStaticText *StaticText31;
    TGroupBox *GroupBox15;
    TLabel *Label32;
    TEdit *edVisnIndexId;
        TGroupBox *GroupBox16;
        TBitBtn *btULD_Vaccum2;
    TImage *Image6;
    TLabel *Label39;
    TLabel *Label40;
    TImage *Image14;
    TLabel *Label37;
    TLabel *Label38;
    TLabel *Label30;
    TLabel *Label43;
    TImage *Image4;
    TLabel *Label35;
    TLabel *Label36;
    TGroupBox *GroupBox22;
    TBitBtn *btULD_Vaccum;
    TGroupBox *GroupBox23;
    TBitBtn *btULD_Ejectr;
    TGroupBox *GroupBox39;
    TBitBtn *btULD_Ejectr2;
    TGroupBox *GroupBox44;
    TBitBtn *btMrkLeftUpPs;
    TBitBtn *btMrkLeftDnPs;
    TBitBtn *btMrkRightUpPs;
    TBitBtn *btMrkRightDnPs;
    TBitBtn *btPSB_TrmXn;
    TBitBtn *btPSB_TrmYp;
    TBitBtn *btPSB_TrmXp;
    TComboBox *cbManualAction;
    TBitBtn *btPSB_TrmYn;
    TImage *Image10;
    TLabel *Label41;
    TLabel *Label42;
    TImage *Image31;
    TLabel *Label33;
    TLabel *Label34;
    TGroupBox *GroupBox45;
    TPanel *pnULD_PprCmp;
    TGroupBox *GroupBox60;
    TPanel *pnULD_PprCmp2;
    TGroupBox *GroupBox76;
    TPanel *pnULD_PprRotator2;
    TGroupBox *GroupBox77;
    TPanel *pnULD_PprRotator;
    TGroupBox *GroupBox69;
    TPanel *pnULD_Cnvs;
    void __fastcall btSavePosClick(TObject *Sender);
    void __fastcall tmUpdateTimerTimer(TObject *Sender);
    void __fastcall FormDestroy(TObject *Sender);
    void __fastcall FormShow(TObject *Sender);
        void __fastcall pcDeviceSetChange(TObject *Sender);
    void __fastcall btPRB_FeedingClick(TObject *Sender);
    void __fastcall rgLDRJogUnitClick(TObject *Sender);
        void __fastcall btULD_VaccumClick(TObject *Sender);
    void __fastcall btULD_Ejectr2Click(TObject *Sender);
    void __fastcall btPSB_TrmYnClick(TObject *Sender);
    bool __fastcall MotorCheck(EN_MOTR_ID _iMotor);
    void __fastcall btPSB_TrmXnClick(TObject *Sender);
    void __fastcall btPSB_TrmXpClick(TObject *Sender);
    void __fastcall btPSB_TrmYpClick(TObject *Sender);
    void __fastcall btMrkLeftUpPsClick(TObject *Sender);
private:	// User declarations
    //Active Radio Button Page.
    TRadioGroup  * rgUnitUser ;
    TEdit        * edUnitUser ;
//    CDelayTimer    m_tmProbeTest ;
public:		// User declarations
    __fastcall TFrmDeviceSet(TComponent* Owner);
    void __fastcall UpdateDevInfo(bool bTo);
    void __fastcall UpdateDevOptn(bool bTo);
    void __fastcall JobFileBackUp();
    double GetMotrPosTable(EN_MOTR_ID _iMotr , int _iRow , int _iCol);

    TFraMotr *FraMotor   [MAX_MOTR];
    TFraCyl  *FraCylinder[MAX_ACTR];

    void __fastcall MtWindowSet();
    void __fastcall AtWindowSet();

};
//---------------------------------------------------------------------------
extern PACKAGE TFrmDeviceSet *FrmDeviceSet;
//---------------------------------------------------------------------------
#endif
