//---------------------------------------------------------------------------
#ifndef FormOperationH
#define FormOperationH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <Buttons.hpp>
//---------------------------------------------------------------------------
//#include "FormPassword.h"
#include <Graphics.hpp>
#include <ComCtrls.hpp>
#include "uRs232c.h"
#include <Grids.hpp>
#include <jpeg.hpp>
class TFrmOperation : public TForm
{
__published:	// IDE-managed Components
    TPanel *Panel1;
    TPanel *pnDataMap;
    TPanel *Panel4;
    TPanel *Panel5;
    TPanel *Panel6;
    TPanel *Panel7;
    TBitBtn *btStart;
    TBitBtn *btStop;
    TBitBtn *btReset;
    TBitBtn *btOperator;
    TPanel *plPassWord;
    TPanel *Panel19;
    TLabel *Label17;
    TBitBtn *btPasswordClose;
    TBitBtn *btEngr;
    TBitBtn *btOper;
    TBitBtn *btMast;
    TPanel *Panel8;
    TPanel *Panel9;
    TPanel *Panel10;
    TPanel *Panel11;
    TPanel *Panel12;
    TPanel *Panel13;
    TPanel *Panel14;
    TPanel *Panel15;
    TListBox *lbErr;
    TPanel *Panel16;
    TPanel *Panel18;
    TTimer *tmUpdate;
    TBitBtn *btLotOpen;
    TBitBtn *btLotEnd;
    TLabel *Label1;
    TLabel *Label3;
    TLabel *Label4;
    TLabel *Label5;
    TLabel *Label6;
    TLabel *Label31;
    TLabel *Label32;
    TPanel *pnDayRunTime;
    TPanel *pnDayIdleTime;
    TPanel *pnDayJamTime;
    TPanel *pnDayTotalTime;
    TPanel *pnDayChipUpeh;
    TPanel *pnDayWorkChip;
    TPanel *pnDayLotCount;
        TPageControl *pcManual;
    TTabSheet *TabSheet1;
    TTabSheet *TabSheet2;
    TTabSheet *TabSheet3;
    TTabSheet *TabSheet4;
    TLabel *Label16;
    TPanel *pnDayFailChip;
    TLabel *Label2;
    TLabel *Label7;
    TLabel *Label8;
    TLabel *Label9;
    TLabel *Label10;
    TLabel *Label33;
    TLabel *Label34;
    TPanel *pnLotNo;
    TPanel *pnLotWorkChip;
    TPanel *pnLotChipUpeh;
    TPanel *pnLotStartTime;
    TPanel *pnLotRunTime;
    TPanel *pnLotFailChip;
    TPanel *pnLotJobFile;
    TTabSheet *TabSheet11;
        TBitBtn *btMan1_1;
        TBitBtn *btMan1_2;
        TBitBtn *btMan1_7;
        TBitBtn *btMan1_3;
        TBitBtn *btMan1_4;
        TBitBtn *btMan1_5;
        TBitBtn *btMan1_6;
        TBitBtn *btMan1_8;
        TBitBtn *btMan1_9;
        TBitBtn *btMan1_10;
        TBitBtn *btMan1_11;
        TBitBtn *btMan1_12;
        TBitBtn *btMan1_13;
        TBitBtn *btMan1_14;
        TBitBtn *btMan2_1;
        TBitBtn *btMan2_2;
        TBitBtn *btMan2_7;
        TBitBtn *btMan2_3;
        TBitBtn *btMan2_4;
        TBitBtn *btMan2_5;
        TBitBtn *btMan2_6;
        TBitBtn *btMan2_8;
        TBitBtn *btMan2_9;
        TBitBtn *btMan2_10;
        TBitBtn *btMan2_11;
        TBitBtn *btMan2_12;
        TBitBtn *btMan2_13;
        TBitBtn *btMan2_14;
        TBitBtn *btMan3_1;
        TBitBtn *btMan3_2;
        TBitBtn *btMan3_7;
        TBitBtn *btMan3_3;
        TBitBtn *btMan3_4;
        TBitBtn *btMan3_5;
        TBitBtn *btMan3_6;
        TBitBtn *btMan3_8;
        TBitBtn *btMan3_9;
        TBitBtn *btMan3_10;
        TBitBtn *btMan3_11;
        TBitBtn *btMan3_12;
        TBitBtn *btMan3_13;
        TBitBtn *btMan3_14;
        TBitBtn *btMan4_1;
        TBitBtn *btMan4_2;
        TBitBtn *btMan4_7;
        TBitBtn *btMan4_3;
        TBitBtn *btMan4_4;
        TBitBtn *btMan4_5;
        TBitBtn *btMan4_6;
        TBitBtn *btMan4_8;
        TBitBtn *btMan4_9;
        TBitBtn *btMan4_10;
        TBitBtn *btMan4_11;
        TBitBtn *btMan4_12;
        TBitBtn *btMan4_13;
        TBitBtn *btMan4_14;
        TBitBtn *btMan5_1;
        TBitBtn *btMan5_2;
        TBitBtn *btMan5_7;
        TBitBtn *btMan5_3;
        TBitBtn *btMan5_4;
        TBitBtn *btMan5_5;
        TBitBtn *btMan5_6;
        TBitBtn *btMan5_8;
        TBitBtn *btMan5_9;
        TBitBtn *btMan5_10;
        TBitBtn *btMan5_11;
        TBitBtn *btMan5_12;
        TBitBtn *btMan5_13;
        TBitBtn *btMan5_14;
        TTabSheet *TabSheet12;
        TBitBtn *btMan7_1;
        TBitBtn *btMan7_8;
        TBitBtn *btMan7_2;
        TBitBtn *btMan7_9;
        TBitBtn *btMan7_3;
        TBitBtn *btMan7_10;
        TBitBtn *btMan7_4;
        TBitBtn *btMan7_11;
        TBitBtn *btMan7_5;
        TBitBtn *btMan7_12;
        TBitBtn *btMan7_6;
        TBitBtn *btMan7_13;
        TBitBtn *btMan7_7;
        TBitBtn *btMan7_14;
    TPanel *Panel32;
    TLabel *Label14;
    TPanel *pnIgnrDoor;
    TPanel *Panel2;
    TLabel *Label13;
        TPanel *pnVisionSkip;
    TPanel *Panel34;
    TLabel *Label15;
    TPanel *pnInspSkip;
    TPanel *Panel22;
    TPanel *pnIgnrVacuum;
    TPanel *Panel25;
    TLabel *Label36;
    TPanel *pnIgnrStrAlm;
    TPanel *Panel23;
    TLabel *Label28;
    TPanel *pnLoadingStop;
    TPanel *Panel21;
    TLabel *Label11;
    TPanel *pnCheckFailCnt;
    TEdit *edLimAllFailCnt;
    TPanel *Panel17;
    TLabel *Label12;
    TPanel *pnIgnoreTrim;
    TLabel *Label27;
        TPageControl *PageControl1;
        TTabSheet *TabSheet5;
        TTabSheet *TabSheet6;
        TLabel *Label47;
        TEdit *edRejectBinNo;
        TGroupBox *GroupBox1;
        TPanel *pnLoader;
        TGroupBox *GroupBox3;
        TLabel *Label37;
        TLabel *Label38;
        TLabel *Label39;
        TPageControl *pcPbz;
        TTabSheet *TabSheet7;
        TPanel *pnPreBuff;
        TEdit *edPrbLotNo;
        TEdit *edPrbMgzNo;
        TEdit *edPrbSlotNo;
        TButton *btPrbLotInput;
        TButton *btPRBInput;
        TButton *btPrbClear;
        TGroupBox *GroupBox4;
        TLabel *Label40;
        TLabel *Label41;
        TLabel *Label42;
        TPageControl *pcPsb;
        TTabSheet *TabSheet9;
        TPanel *pnPostBuff;
        TButton *btPsbClear;
        TEdit *edPsbLotNo;
        TButton *btPsbLotInput;
        TEdit *edPsbSlotNo;
        TEdit *edPsbMgzNo;
        TGroupBox *GroupBox5;
        TLabel *Label43;
        TLabel *Label44;
        TLabel *Label45;
        TPageControl *pcIns;
        TTabSheet *TabSheet8;
        TPanel *pnWorkZone;
        TButton *btInspClear;
        TEdit *edInspLotNo;
        TButton *btInspLotInput;
        TEdit *edInspSlotNo;
        TEdit *edInspMgzNo;
        TGroupBox *GroupBox6;
        TLabel *Label26;
        TLabel *Label29;
        TLabel *Label30;
        TLabel *Label35;
        TEdit *edWork;
        TEdit *edFailTotal;
        TEdit *edLotNo;
        TEdit *edTime;
        TEdit *edRjtBinNoInput;
        TButton *btSetBinCnt;
        TBitBtn *BitBtn1;
        TBitBtn *BitBtn2;
        TPanel *Panel3;
        TLabel *lbCnt;
        TLabel *lbCntRe;
        TGroupBox *GroupBox2;
        TPanel *pnUnLoader;
        TPanel *pnOperVisn;
        TLabel *lbMgzCnt;
        TPanel *pnTmpr_NotVsn;
        TLabel *Label18;
        TLabel *Label19;
        TLabel *Label20;
        TLabel *Label21;
        TLabel *Label22;
        TLabel *Label23;
        TLabel *Label24;
        TLabel *Label54;
        TEdit *edTemp1_NotVsn;
        TButton *btTemp1_NotVsn;
        TEdit *edTemp2_NotVsn;
        TButton *btTemp2_NotVsn;
        TEdit *edTemp3_NotVsn;
        TButton *btTemp3_NotVsn;
        TEdit *edTemp4_NotVsn;
        TButton *btTemp4_NotVsn;
        TEdit *edTemp5_NotVsn;
        TButton *btTemp5_NotVsn;
        TEdit *edTemp6_NotVsn;
        TButton *btTemp6_NotVsn;
        TEdit *edTemp7_NotVsn;
        TButton *btTemp7_NotVsn;
        TEdit *edTempAll_NotVsn;
        TButton *btTempAll_NotVsn;
        TButton *btOK_NotVsn;
        TGroupBox *GroupBox15;
        TPanel *pnCrtTMPR1_NotVsn;
        TPanel *pnSetTMPR1_NotVsn;
        TGroupBox *GroupBox16;
        TPanel *pnSetTMPR2_NotVsn;
        TPanel *pnCrtTMPR2_NotVsn;
        TGroupBox *GroupBox17;
        TPanel *pnSetTMPR3_NotVsn;
        TPanel *pnCrtTMPR3_NotVsn;
        TGroupBox *GroupBox18;
        TPanel *pnSetTMPR4_NotVsn;
        TPanel *pnCrtTMPR4_NotVsn;
        TGroupBox *GroupBox19;
        TPanel *pnSetTMPR5_NotVsn;
        TPanel *pnCrtTMPR5_NotVsn;
        TGroupBox *GroupBox20;
        TPanel *pnSetTMPR6_NotVsn;
        TPanel *pnCrtTMPR6_NotVsn;
        TGroupBox *GroupBox21;
        TPanel *pnSetTMPR7_NotVsn;
        TPanel *pnCrtTMPR7_NotVsn;
        TPanel *pnTemperature;
        TLabel *Label25;
        TLabel *Label46;
        TLabel *Label48;
        TLabel *Label49;
        TLabel *Label50;
        TLabel *Label51;
        TLabel *Label52;
        TLabel *Label55;
        TEdit *edTemp1;
        TButton *btTemp1;
        TEdit *edTemp2;
        TButton *btTemp2;
        TEdit *edTemp3;
        TButton *btTemp3;
        TEdit *edTemp4;
        TButton *btTemp4;
        TEdit *edTemp5;
        TButton *btTemp5;
        TEdit *edTemp6;
        TButton *btTemp6;
        TEdit *edTemp7;
        TButton *btTemp7;
        TEdit *edTempAll;
        TButton *btTempAll;
        TButton *btOK;
        TGroupBox *GroupBox7;
        TPanel *pnCrtTMPR1;
        TPanel *pnSetTMPR1;
        TGroupBox *GroupBox8;
        TPanel *pnSetTMPR2;
        TPanel *pnCrtTMPR2;
        TGroupBox *GroupBox9;
        TPanel *pnSetTMPR3;
        TPanel *pnCrtTMPR3;
        TGroupBox *GroupBox13;
        TPanel *pnSetTMPR4;
        TPanel *pnCrtTMPR4;
        TGroupBox *GroupBox12;
        TPanel *pnSetTMPR5;
        TPanel *pnCrtTMPR5;
        TGroupBox *GroupBox11;
        TPanel *pnSetTMPR6;
        TPanel *pnCrtTMPR6;
        TGroupBox *GroupBox10;
        TPanel *pnSetTMPR7;
        TPanel *pnCrtTMPR7;
    void __fastcall FormShow(TObject *Sender);
    void __fastcall btOperatorClick(TObject *Sender);
    void __fastcall btPasswordCloseClick(TObject *Sender);
    void __fastcall btOperClick(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall tmUpdateTimer(TObject *Sender);
        void __fastcall btLotOpenClick(TObject *Sender);
        void __fastcall btStartClick(TObject *Sender);
        void __fastcall btStopClick(TObject *Sender);
        void __fastcall btResetClick(TObject *Sender);
        void __fastcall btLotEndClick(TObject *Sender);
    void __fastcall pnIgnoreTrimDblClick(TObject *Sender);
    void __fastcall btMan1_1Click(TObject *Sender);
        void __fastcall btPrbClearClick(TObject *Sender);
        void __fastcall btInspClearClick(TObject *Sender);
        void __fastcall btPsbClearClick(TObject *Sender);
    void __fastcall btPrbLotInputClick(TObject *Sender);
    void __fastcall edLimAllFailCntChange(TObject *Sender);
        void __fastcall btPRBInputClick(TObject *Sender);
    void __fastcall pnDayRunTimeDblClick(TObject *Sender);
    void __fastcall GroupBox1Click(TObject *Sender);
    void __fastcall btSetBinCntClick(TObject *Sender);
        void __fastcall BitBtn1Click(TObject *Sender);
        void __fastcall BitBtn2Click(TObject *Sender);
        void __fastcall btOKClick(TObject *Sender);
        void __fastcall pnCrtTMPR1DblClick(TObject *Sender);
        void __fastcall btTemp1_NotVsnClick(TObject *Sender);

private:	// User declarations

public:		// User declarations
    __fastcall TFrmOperation(TComponent* Owner);
    bool __fastcall CheckStripDisappear();
    bool __fastcall CheckStripUnknwon  ();
};
//---------------------------------------------------------------------------
extern PACKAGE TFrmOperation *FrmOperation;
//---------------------------------------------------------------------------
#endif
